@startuml
title Edit Complain Type
|Admin|
start 
    : Select Update Complain Type;
|System|
    :Show Complain Type Update Form;
|Admin|  
    : Admin Update Complain Type;
    : Admin Click Button;
|System|
If () then (Submit)
    :Check Form Validity;
    if () is (Valid) then
        : System Update Complain Type;
        : Show Success Update Complain Type Message;
    else (Not Valid)
        : Show Complain Type Form Errors Message;
    endif
else (Back)
    : Go Back to view All Complain Types Page;
endif
stop
@enduml