@startuml
title View All Complain Types 
|Admin|
start 
    :Admin Click See All Complain Types;
|System|
    :System Retrieves All Complain Types Data;
    :Show All Complain Types Page;
    stop

@enduml