@startuml
title User Delete/Ban(Admin)
|Admin|
start 
    :Select Delete/Ban User Button;
|System|
    :Show Delete/Ban User Confirmation;
|Admin|
    :Admin Click on Button;
    |System|
If () then (Confirm)
    : System Update Selected User status to Banned;
    : Show Success Deleting User Message;
else (Back)
    : Go Back to view All Boarding Management Page;  
endif
stop
@enduml