@startuml
title Boarding House End Rent (Tenant)

|Tenant|
start
    : Select End Rent Boarding House;

|System|
    : Show End Rent Boarding House Details;

|Tenant|
    : Fill Tenant End Rent Boarding House Details;
    : Tenant Click Button;
|System|
If () then (Confirm)
    : Check Form Validity;
    if () is (Valid) then
        : System Update Selected Boarding End Rent Date;
        : Show Success End Rent Boarding House Message;
    else (Not Valid)
        : Show End Rent Boarding Form Errors Message;
    endif
else (Back)
    : Go Back to All Boarding Houses History Page (Tenant);
endif
stop 
@enduml