@startuml

|Tenant|
start
:Open Payment List Page;

|Website|
:Show Payment List Page;

|Tenant|
:Select One Payment From the List;

|Website|
:Show Payment Details;

|Tenant|
:Select Payment Method;

|Website|
:Show Upload Payment Receipt/Proof;

|Tenant|
repeat
:Upload Payment Receipt/Proof;
|Website|
repeat while (Verify Image) is (Invalid)
        ->Valid;
    :Insert Payment Receipt/Proof to Storage;
    :Update Payment Status;
    :Show Payment List Page;
stop
@enduml