@startuml
title Start Rent Boarding House
|User|
start
    :View selected boarding house detail;

|System|
    :Show selected boarding house detail page;

|User|
    :Fill in Start Rent Date;
    :Click Rent Button;

|System|
    :Check Form Validity;
    if () is (Valid) then
        :Add details to tenantBoardings;
        :Redirect user to selected boarding house detail page;
    else (Not Valid)
        : Show Start Rent Boarding Form Errors Message;
    endif
    
stop

@enduml