@startuml
title Approve Reject Payment Remit
|Admin|
start
    :Select Check Invoice Page;
|Website|
    :Retrieve Processing Payment;
    :Return Check Invoice Page;
|Admin|
    :Select Approve or Reject Button;    
if (Admin Approve) is (Approve) then
    :Admin Upload Proof of Transfer Image;
else (Reject)
    :Admin Give Reason for Rejection;
|Website|
    :Send Rejection Message;
endif
    :Update Payment Status in DB;
    :Show Message;
stop
@enduml