@startuml
title Boarding Type Delete (Admin)
|Admin|
start 
    : Admin Press Delete Boarding Type Button;
|System|
    : Show Delete Confirmation;
|Admin|
    : Admin Click Button;
|System|
If () then (Confirm)
    : System Delete Boarding Type;
    : Show Success Delete Boarding Type Message;
else (Back)
    : Go Back to view All Boarding Types Management Page;
endif
stop
@enduml