@startuml
title Boarding Type Update (Admin)
|Admin|
start 
    : Select Update Boarding Type;
|System|
    :Show Boarding Type Update Form;
|Admin|  
    : Admin Update Boarding Type;
    : Admin Click Button;
|System|
If () then (Submit)
    :Check Form Validity;
    if () is (Valid) then
        : System Update Boarding Type;
        : Show Success Update Boarding Type Message;
    else (Not Valid)
        : Show Boarding Type Form Errors Message;
    endif
else (Back)
    : Go Back to view All Boarding Types Management Page;
endif
stop
@enduml