@startuml
title View All Boarding Types
|Admin|
start 
    :Admin Click See All Boarding Types;
|System|
    :System Retrieves All Boarding Types Data;
    :Show All Boarding Types Page;
    stop

@enduml