@startuml
title Cancel Payment
actor "actin" as act
participant ":CheckInvoiceRequest\n<<UI>>" as view
participant PaymentController as pctrl
participant ChatController as cctrl
participant TransactionModel as tm

act -> view : getTransactionDetailPage()
view -> pctrl : getTransactionDetail(invoice_id)
pctrl -> tm : getTransaction(invoice_id)
pctrl <-- tm : transaction_data
view <-- pctrl : displayTransactionDetail(transaction_data)

act -> view : cancelTransaction()
view -> pctrl : cancelTransaction(invoice_id)
pctrl -> tm : getTransaction(invoice_id)
pctrl <-- tm : transaction_data

alt (Transfer Status is Successful or Transaction Type is Down Payment)
    pctrl -> pctrl : rejectCancel()
else (Payment Status is Approve)
    pctrl -> tm : updatePaymentStatus(invoice_id)
    pctrl -> tm : updateTransactionStatus(invoice_id)
    pctrl -> cctrl : storeSpecificChatMessage(tenant_id, reason)
    
else (Payment Status is Pending or Rejected)
    pctrl -> tm : updatePaymentStatus(invoice_id)
else (Payment Status is Processing)
    pctrl -> tm : updateTransactionStatus(invoice_id)
end
view <-- pctrl : response_message
act <-- view : displayResponseMessage(response_message)

@enduml
