@startuml
title Make Down Payment Invoice
actor "Owner & Manager" as act
participant ":ViewAllPayments\n<<UI>>" as view
participant PaymentController as ctrl
participant TransactionModel as tm

act -> view : openDownPaymentPage()
view -> ctrl : getDownPaymentPage(tenant_boarding_id)
view <-- ctrl : payment_detail_data
act <-- view : displayAddDownPaymentPage(payment_detail_data) 

act -> view : addDownPaymentInformation()
view -> ctrl : addDownPayment(payment_information)
ctrl -> ctrl : validatePaymentInput(payment_information)
ctrl -> ctrl : generateInvoice(payment_information)

alt (Payment Input Valid)
    ctrl -> tm : insertPayment(payment_information)
    view <-- ctrl : response_message
    act <-- view : displayResponseMessage(response_message) 

else (Payment Input Invalid)
    view <-- ctrl : displayInputInvalid()
end

@enduml
