@startuml
actor Admin as act
participant EndRentBoardingPage as view
participant BoardingController as ctrl
participant BoardingModel as model

act -> view : openEndRentBoardingPage()
view -> ctrl : getEndRentBoardingPage(tenant_boarding_id)
ctrl -> model : EndRentBoardingPageGet(tenant_boarding_id)
model --> ctrl : tenant_boarding_data
ctrl --> view : tenant_boarding_data
view --> act : displayEndRentBoardingPage(tenant_boarding_data)

    act->view : inputEndRentBoardingForm(tenant_boarding_data)
    view->ctrl : validateBoardingData(tenant_boarding_data)
        alt Valid
        ctrl-->view:input_validated_response
        view->ctrl: EndRentBoarding(tenant_boarding_data)
        ctrl->model: EndRentBoarding(tenant_boarding_data)
        model --> ctrl: success_response
        ctrl --> view: success_response
        view-->act: displayAllBoardingsHistoryPage(success_response)
        else Not Valid
        ctrl --> view: error_response
        view-->act: getEndRentBoardingPage(error_response)
        end


@enduml
