@startuml
title Edit Boarding House
actor Admin as act
participant UpdateBoardingPage as view
participant BoardingController as ctrl
participant BoardingModel as model

act -> view : openUpdateBoardingPage()
view -> ctrl : getUpdateBoardingPage(boarding_id)
ctrl -> model : updateBoardingPageGet(boarding_id)
model --> ctrl : boarding_data
ctrl --> view : boarding_data
view --> act : displayUpdateBoardingPage(boarding_data)

    act->view : inputUpdateBoardingForm(boarding_data)
    view->ctrl : validateBoardingData(boarding_data)
        alt Valid
        ctrl-->view:input_validated_response
        view->ctrl: updateBoarding(boarding_data)
        ctrl->model: updateBoarding(boarding_data)
        model --> ctrl: success_response
        ctrl --> view: success_response
        alt user:Auth == Admin
            view-->act: displayAllBoardingsPage(success_response)
            else user:Auth == Owner
            view-->act: displayAllBoardingsOwnPage(success_response)
            end
        else Not Valid
        ctrl --> view: error_response
        view-->act: getUpdateBoardingPage(error_response)
        end


@enduml
