@startuml
actor Admin as act
participant DeleteBoardingConfirmationPage as view
participant BoardingController as ctrl
participant BoardingModel as model

act -> view : getDeleteBoardingConfirmationPage()
act <-- view : displayDeleteBoardingConfirmationPage()

    act->view : inputDeleteBoardingConfirmationForm()
    alt Confirm
        view->ctrl: deleteBoarding(id)
        ctrl->model: deleteBoarding(id)
        model --> ctrl: success_response
        ctrl --> view: success_response
        view-->act: displayAllBoardingAdminPage(success_response)
    else Back
        view-->act: displayAllBoardingAdminPage()
    end

@enduml
