@startuml
actor Admin as act
participant RequestBoardingPage as view
participant BoardingController as ctrl
participant BoardingModel as model

act -> view : getRequestBoardingPage()
act <-- view : displayRequestBoardingPage()

    act->view : inputRequestBoardingForm()
        alt Approved
        view->ctrl: requestBoarding(status:Approved)
        ctrl->model: requestBoarding(status:Approved)
        model --> ctrl: success_response
        ctrl --> view: success_response
        view-->act: displayAllBoardingAdminPage(success_response)
        else Declined (Cannot Reapprove)
        view->ctrl: requestBoarding(status:Banned)
        ctrl->model: requestBoarding(status:Banned)
        model --> ctrl: success_response
        ctrl --> view: success_response
        view-->act: displayAllBoardingAdminPage(success_response)
        else Declined (Can Reapprove)
        view->ctrl: requestBoarding(status:Declined)
        ctrl->model: requestBoarding(status:Declined)
        model --> ctrl: success_response
        ctrl --> view: success_response
        view --> act: displayAllBoardingAdminPage(success_response)
        end


@enduml
