@startuml
title View All Boarding House Management
actor Admin as act
participant ViewAllBoardingManagementPage as view
participant BoardingController as ctrl
participant BoardingModel as model

act -> view: openAllBoardingsManagementPage()
view -> ctrl: getAllBoardingsManagement()
ctrl -> model: getAllBoardinsgFromDB()
ctrl <-- model: all_boarding_houses
view <-- ctrl: all_boarding_houses
act <-- view: displayAllBoardingsManagementPage(all_boarding_houses)

@enduml