@startuml
title Filter Boarding Types
actor Admin as act
participant ViewAllBoardingTypesPage as view
participant BoardingTypeController as ctrl
participant BoardingTypeModel as model

act -> view : FillinFilterSearchForm()
view -> ctrl: getAllBoardingTypesWithFilter()
ctrl -> model: getAllBoardingTypesWithFilter()
ctrl <-- model: all_boarding_types_filtered
view <-- ctrl: all_boarding_types_filtered
act <-- view: displayAllBoardingTypes(all_boarding_types_filtered)

@enduml