@startuml
title Filter Boarding Houses
actor Manager as act
participant ViewAllBoardingHousesPage as view
participant BoardingHouseController as ctrl
participant BoardingHouseModel as model

act -> view : FillinFilterSearchForm()
view -> ctrl: getAllBoardingHousesWithFilter()
ctrl -> model: getAllBoardingHousesWithFilter()
ctrl <-- model: all_boarding_houses_filtered
view <-- ctrl: all_boarding_houses_filtered
act <-- view: displayAllBoardingHouses(all_boarding_houses_filtered)

@enduml