@startuml
title Filter Complain Types
actor Admin as act
participant ViewAllComplainTypesPage as view
participant ComplainTypeController as ctrl
participant ComplainTypeModel as model

act -> view : FillinFilterSearchForm()
view -> ctrl: getAllComplainTypesWithFilter()
ctrl -> model: getAllComplainTypesWithFilter()
ctrl <-- model: all_complain_types_filtered
view <-- ctrl: all_complain_types_filtered
act <-- view: displayAllComplainTypes(all_complain_types_filtered)

@enduml