@startuml
title Filter Facility Details
actor Admin as act
participant ViewAllFacilityDetailsPage as view
participant FacilityDetailController as ctrl
participant FacilityDetailModel as model

act -> view : FillinFilterSearchForm()
view -> ctrl: getAllFacilityDetailsWithFilter()
ctrl -> model: getAllFacilityDetailsWithFilter()
ctrl <-- model: all_facility_details_filtered
view <-- ctrl: all_facility_details_filtered
act <-- view: displayAllFacilityDetails(all_facility_details_filtered)

@enduml