@startuml
title Filter Payment Methods
actor Admin as act
participant ViewAllPaymentMethodsPage as view
participant PaymentMethodController as ctrl
participant PaymentMethodModel as model

act -> view : FillinFilterSearchForm()
view -> ctrl: getAllPaymentMethodsWithFilter()
ctrl -> model: getAllPaymentMethodsWithFilter()
ctrl <-- model: all_payment_methods_filtered
view <-- ctrl: all_payment_methods_filtered
act <-- view: displayAllPaymentMethods(all_payment_methods_filtered)

@enduml