@startuml
title Filter Tenants
actor Manager as act
participant ViewAllTenantsPage as view
participant TenantController as ctrl
participant TenantModel as model

act -> view : FillinFilterSearchForm()
view -> ctrl: getAllTenantsWithFilter()
ctrl -> model: getAllTenantsWithFilter()
ctrl <-- model: all_tenants_filtered
view <-- ctrl: all_tenants_filtered
act <-- view: displayAllTenants(all_tenants_filtered)

@enduml