@startuml
title Filter TransactionTypes
actor Admin as act
participant ViewAllTransactionTypesPage as view
participant TransactionTypeController as ctrl
participant TransactionTypeModel as model

act -> view : FillinFilterSearchForm()
view -> ctrl: getAllTransactionTypesWithFilter()
ctrl -> model: getAllTransactionTypesWithFilter()
ctrl <-- model: all_transaction_types_filtered
view <-- ctrl: all_transaction_types_filtered
act <-- view: displayAllTransactionTypes(all_transaction_types_filtered)

@enduml