@startuml
title Filter Users
actor Manager as act
participant ViewAllUsersPage as view
participant UserController as ctrl
participant UserModel as model

act -> view : FillinFilterSearchForm()
view -> ctrl: getAllUsersWithFilter()
ctrl -> model: getAllUsersWithFilter()
ctrl <-- model: all_users_filtered
view <-- ctrl: all_users_filtered
act <-- view: displayAllUsers(all_users_filtered)

@enduml