@startuml
actor Owner as act
participant EnableBoardingConfirmationPage as view
participant BoardingController as ctrl
participant BoardingModel as model

act -> view : getEnableBoardingConfirmationPage()
act <-- view : displayEnableBoardingConfirmationPage()

    act->view : inputEnableBoardingForm()
    view->ctrl: enableBoarding(status:Approved)
    ctrl->model: enableBoarding(status:Approved)
    model --> ctrl: success_response
    ctrl --> view: success_response
    view-->act: displayAllBoardingsOwnPage(success_response)

@enduml
