@startuml
title View All Facility Details
|Admin|
start 
    :Admin Click See All Facility Details;

|System|
    :System Retrieves All Facility Details Data;
    :Show All Facility Details Page;
    stop

@enduml