@startuml
title Edit Facility Detail
|Admin|
start 
    : Select Update Facility Details;
|System|
    :Show Boarding House Details;
|Admin|  
    : Admin Update Facility Details;
    : Admin Click Button;
|System|
If () then (Submit)
    :Check Form Validity;
    if () is (Valid) then
        : System Update Selected Facility Details;
        : Show Success Update Facility Details Message;
        stop
    else (Not Valid)
        : Show Facility Details Form Errors Message;
        stop
    endif
else (Back)
    : Go Back to view All Facility Details Page;
    stop  
endif
@enduml