@startuml
title Facility Details Management View All (Admin)
|Admin|
start 
    :Admin Click See All Facility Details;

|System|
    :System Retrieves All Facility Details Data;
    :Show All Facility Details Management Page (Admin);
    stop

@enduml