@startuml
title Boarding House Update (Owner)

|Owner|
start
    : Select Update Boarding House;

|System|
    : Show Boarding House Details;

|Owner|
    : Owner Update Boarding House Details;
    : Owner Click Button;
|System|
If () then (Confirm)
    : Check Form Validity;
    if () is (Valid) then
        : System Update Selected Boarding House;
        : Show Success Update Boarding House Message;
    else (Not Valid)
        : Show Boarding Form Errors Message;
    endif
else (Back)
    : Go Back to view All Boarding Management Page;
endif
stop 
@enduml