@startuml
title User Update (Admin)
|Admin|
start 
    : Select Update User;
|System|
    :Show Boarding House Details;
|Admin|  
    : Admin Update User;
    : Admin Click Button;
|System|
If () then (Submit)
    :Check Form Validity;
    if () is (Valid) then
        : System Update Selected User;
        : Show Success Update User Message;
    else (Not Valid)
        : Show User Form Errors Message;
    endif
else (Back)
    : Go Back to view All User Management Page;  
endif
stop
@enduml