@startuml
title Boarding House History Tenant
actor Admin as act
participant ViewAllBoardingHistoryPage as view
participant BoardingController as ctrl
participant BoardingModel as model

act -> view: openAllBoardingsHistoryPage()
view -> ctrl: getAllBoardingsHistory()
ctrl -> model: getAllBoardingsHistoryFromDB()
ctrl <-- model: all_boarding_houses_history
view <-- ctrl: all_boarding_houses_history
act <-- view: displayAllBoardingsHistoryPage(all_boarding_houses_history)

@enduml