@startuml
left to right direction
skinparam linetype ortho

rectangle BHFMS {
    ' General'
    usecase (Chat) as cht
    usecase (Login) as lgn
    usecase (Register) as rgs
    usecase (Logout) as logout
    usecase (Edit Profile) as edt_profile
    usecase (View Payment History) as view_ph
    usecase (View Payment History Detail) as view_ph_detail
    
    ' Manager'
    usecase (View Complains) as view_cmpln
    usecase (Change Complain Status) as chng_cmpln
    usecase (View All Tenant) as view_tenant
    usecase (Tenant Request) as accept_tenant
    usecase (View Boarding House Own By Manager) as view_bh_own_mng
    usecase (View Tenant Detail) as view_tenant_detail

    usecase (Make Payment Invoice) as mk_pay_inv
    usecase (Edit Payment Invoice) as edit_pay_inv
    usecase (Cancel Payment Invoice) as cancel_pay_inv

    ' Boarding House Owner'
    usecase (Request New Boarding) as req_bh
    usecase (Reapprove Boarding) as reapv_bh
    usecase (Disable Boarding) as dis_bh
    usecase (Enable Boarding) as enb_bh
    usecase (Edit Boarding House) as edit_bh
    usecase (View Boarding House Own By Owner) as view_bh_own_own

    ' Tenant'
    usecase (Start Rent Boarding House) as rent_bh
    usecase (End Rent Boarding House) as end_rent_bh
    usecase (Add Wishlist Boarding House) as add_wish_bh
    usecase (View Wishlist Boarding House) as view_wish_bh
    usecase (Delete Wishlist Boarding House) as del_wish_bh
    usecase (Search Boarding House) as search_bh
    usecase (Pay Rent) as rpymnt
    usecase (Make Complain) as cmpln
    usecase (Make Review) as mk_rvw
    usecase (View Review) as vw_rvw
    usecase (Update Review) as update_rvw
    usecase (View All Boarding House) as show_bh_all
    usecase (View Boarding House Detail) as show_bh_detail
    usecase (Boarding House History Tenant) as view_bh_tenant

    ' Supervisor / Admin'
    usecase (View All Boarding House Management) as show_bh_admin
    usecase (Ban Boarding House) as del_bh_admin
    usecase (Boarding House Request) as aprv_bh_admin
    usecase (View Boarding House Detail Management) as view_bh

    usecase (View All Facility Details) as show_fcl_admin 
    usecase (Delete Facility Detail) as del_fcl_admin
    usecase (Edit Facility Detail) as edit_fcl_admin
    usecase (Add Facility Detail) as aprv_fcl_admin
    
    usecase (View All Users) as show_user_admin 
    usecase (Ban User) as del_user_admin
    usecase (Edit User) as edit_user_admin
    usecase (View User Detail) as view_user_admin

    usecase (View All Boarding Types) as show_btyp_admin 
    usecase (Delete Boarding Type) as del_btyp_admin
    usecase (Edit Boarding Type) as edit_btyp_admin
    usecase (Add Boarding Type) as aprv_btyp_admin

    usecase (View All Complain Types) as show_ctyp_admin 
    usecase (Delete Complain Type) as del_ctyp_admin
    usecase (Edit Complain Type) as edit_ctyp_admin
    usecase (Add Complain Type) as aprv_ctyp_admin

    usecase (View All Payment Methods) as show_pymtd_admin 
    usecase (Delete Payment Method) as del_pymtd_admin
    usecase (Edit Payment Method) as edit_pymtd_admin
    usecase (Add Payment Method) as aprv_pymtd_admin

    usecase (View All Transaction Types) as show_ttyp_admin 
    usecase (Delete Transaction Type) as del_ttyp_admin
    usecase (Edit Transaction Type) as edit_ttyp_admin
    usecase (Add Transaction Type) as aprv_ttyp_admin
    
    usecase (View All Payment History) as view_payment
    usecase (Accept Payment) as accpt_payment


    usecase (Filter Boarding Houses) as filter_bh
    usecase (Filter Facility Details) as filter_fcl
    usecase (Filter Boarding Types) as filter_bh_type
    usecase (Filter Complain Types) as filter_cmpl_type
    usecase (Filter Tenants) as filter_tnt
    usecase (Filter Payment Methods) as filter_pym_mtd
    usecase (Filter Transaction Types) as filter_tr_typ
    usecase (Filter Users) as filter_user

    usecase (View Payment Invoice) as show_pi_admin
    usecase (Approve / Reject Payment Invoice) as aprv_rjct_pi_admin
    usecase (View All Payment Support) as show_ps_admin
    usecase (View Payment Remit) as show_pr_admin
    usecase (Approve / Reject Payment Remit) as aprv_rjct_pr_admin
}

actor :Owner: as own
actor :User: as user
actor :Tenant: as tenant
actor :Admin: as adm
actor :Manager: as mngr

adm ---> logout
tenant ---> logout
mngr ---> logout

adm ---> edt_profile
tenant ---> edt_profile
mngr ---> edt_profile

user <|-right- mngr
mngr <|-right- own
user <|-right- tenant
user <|-right- adm




adm ---> lgn
tenant ---> lgn
mngr ---> lgn

adm ---> cht
tenant ---> cht
mngr ---> cht

user ---> rgs
mngr ---> rgs

mngr ---> view_ph
tenant ---> view_ph
view_ph <... view_ph_detail: <<Extend>>

adm ---> show_bh_admin
adm ---> show_fcl_admin
adm ---> show_pi_admin
adm ---> show_ps_admin
adm ---> show_pr_admin
show_pi_admin <... aprv_rjct_pi_admin: <<Extend>>
show_pi_admin <... view_ph_detail: <<Extend>>
show_ps_admin <... view_ph_detail: <<Extend>>
show_pr_admin <... aprv_rjct_pr_admin: <<Extend>>

tenant ---> rpymnt
tenant ---> rent_bh
tenant ---> cmpln
tenant ---> mk_rvw
tenant ---> vw_rvw
tenant ---> view_cmpln
tenant ---> add_wish_bh
tenant ---> view_wish_bh
tenant ---> view_bh_tenant
view_bh_tenant <... view_bh: <<Extend>>
view_bh_tenant <... end_rent_bh: <<Extend>>
view_wish_bh <... del_wish_bh: <<Extend>>

user ---> show_bh_all
user ---> search_bh

vw_rvw <... update_rvw: <<Extend>>
show_bh_all <... show_bh_detail: <<Extend>>

mngr ---> mk_pay_inv
mk_pay_inv ...> edit_pay_inv: <<Extend>>
mk_pay_inv ...> cancel_pay_inv: <<Extend>>

view_cmpln <... chng_cmpln: <<Extend>>
view_bh_own_own <... edit_bh: <<Extend>>
show_bh_admin <.. edit_bh: <<Extend>>

own ---> view_bh_own_own
view_bh_own_own <... req_bh: <<Extend>>
view_bh_own_own <... reapv_bh: <<Extend>>
view_bh_own_own <... dis_bh: <<Extend>>
view_bh_own_own <... enb_bh: <<Extend>>

show_bh_admin <... del_bh_admin: <<Extend>>

show_bh_admin <... aprv_bh_admin: <<Extend>>
show_bh_admin <... view_bh: <<Extend>>

show_fcl_admin <... del_fcl_admin: <<Extend>>
show_fcl_admin <... edit_fcl_admin: <<Extend>>
show_fcl_admin <... aprv_fcl_admin: <<Extend>>

adm ---> show_user_admin
show_user_admin <... del_user_admin: <<Extend>>
show_user_admin <... edit_user_admin: <<Extend>>
show_user_admin <... view_user_admin: <<Extend>>

adm ---> show_btyp_admin
show_btyp_admin <... del_btyp_admin: <<Extend>>
show_btyp_admin <... edit_btyp_admin: <<Extend>>
show_btyp_admin <... aprv_btyp_admin: <<Extend>>

adm ---> show_ctyp_admin
show_ctyp_admin <... del_ctyp_admin: <<Extend>>
show_ctyp_admin <... edit_ctyp_admin: <<Extend>>
show_ctyp_admin <... aprv_ctyp_admin: <<Extend>>

adm ---> show_pymtd_admin
show_pymtd_admin <... del_pymtd_admin: <<Extend>>
show_pymtd_admin <... edit_pymtd_admin: <<Extend>>
show_pymtd_admin <... aprv_pymtd_admin: <<Extend>>

adm ---> show_ttyp_admin
show_ttyp_admin <... del_ttyp_admin: <<Extend>>
show_ttyp_admin <... edit_ttyp_admin: <<Extend>>
show_ttyp_admin <... aprv_ttyp_admin: <<Extend>>

mngr -->view_tenant
mngr --> view_cmpln
mngr --> view_bh_own_mng
note left
Can only be 
Accessed by Manager
end note
view_bh_own_mng <... view_bh: <<Extend>>


view_tenant <...  accept_tenant: <<Extend>>
view_tenant <... view_tenant_detail: <<Extend>>

' Filters
view_tenant <.. filter_tnt: <<Extend>>
view_bh_own_mng <.. filter_bh: <<Extend>>
view_bh_own_own <.. filter_bh: <<Extend>>
show_bh_admin <.. filter_bh: <<Extend>>
view_bh_tenant <.. filter_bh: <<Extend>>
show_fcl_admin <.. filter_fcl: <<Extend>>
show_user_admin <.. filter_user: <<Extend>>
show_btyp_admin <.. filter_bh_type: <<Extend>>
show_ctyp_admin <.. filter_cmpl_type: <<Extend>>
show_pymtd_admin <.. filter_pym_mtd: <<Extend>>
show_ttyp_admin <.. filter_tr_typ: <<Extend>>
@enduml
