@startuml
' Controller
class AuthController {
    +getRegisterPage()
    +getLoginPage()
    +register(request)
    +login(request)
    +logout(request)
}

class BoardingController {
    +getMainPage()
    +indexAdmin(request)
    +indexManager(request)
    +indexOwner(request)
    +indexTenant(request)
    +getAllBoardingHouse()
    +getBoardingHouseDetail(request)
    +searchBoardingByLocation(request)
    +getCreateOwnerBoarding()
    +createOwnerBoarding(request)
    +getReadBoarding(request)
    +getReadingBoardingTenant(request)
    +getUpdateBoarding(request)
    +updateBoarding(request)
    +deleteBoarding(request)
    +boardingRent(request)
    +getAdminApproveBoarding(request)
    +adminApproveBoarding(request)
    +getReapproveBoarding(request)
    +reapproveBoarding(request)
    +disableBoardingOwner(request)
    +enableBoardingOwner(request)
}

class BoardingImageController {
    +deleteImage(request)
}

class BoardingTypeController {
    +getAllBoardingTypePage(request)
    +getBoardingTypeCreate()
    +boardingTypeCreate(request)
    +getBoardingTypeUpdate(request)
    +boardingTypeUpdate(request)
    +boardingTypeDelete(request)
}

class ChatController {
    +getChatPage()
    +getChatMessage(request)
    +storeChatMessage(request)
    +storeSpecificChatMessage()
}

class ComplainController {
    +getComplainListPage()
    +getCreateComplainPage()
    +createComplain(request)
    +getComplainDetail(request)
    +setComplainStatus(request)
    +getOwnerComplainPage()
    +getSelectedBoardingHouseComplainList(request)
}

class ComplainTypeController {
    +getAllComplainTypePage(request)
    +getComplainTypeCreate()
    +complainTypeCreate(request)
    +getComplainTypeUpdate(request)
    +complainTypeUpdate(request)
    +complainTypeDelete(request)
}

class FacilityController {
    +getAllFacilitypage(request)
    +getFacilityCreate()
    +facilityCreate(request)
    +getFacilityUpdate(request)
    +facilityUpdate(request)
    +facilityDelete(request)
}
class PaymentController {
    +addPaymentTenant(request)
    +addPaymentManager(request)
    +addDownPayment(request)
    +getPaymentPageManager()
    +getCheckInvoiceRequest()
    +getInvoiceListProcessing()
    +getAllPayment()
    +getInvoiceDetail(request)
    +getEditPayment()
    +getDownPayment()
    +getPaymentPageTenant()
    +getPaymentRemit()
    +getPaymentSupport()
    +cancelPayment()
    +updateInvoiceStatus(request)
    +updatePayment(request)
    +editDownPayment(request)
    +updateTransferredStatus(request)
    -generateInvoice(date)
    -getBoardingHouseName(boardingId)
    -getTransactionTypeName()
    -getAllTenants(boardingId)
    -getTenantBoarding(tenantBoarding)
    -getTenantIdByEmail(email, boardingId)
    -getListPaymentByUser(userId)
    -getListPaymentByBoardingId(boardingId)
    -getTenantById(tenantId)
}

class PaymentMethodController {
    +getAllPaymentMethodPage(request)
    +getPaymentMethodCreate()
    +paymentMethodCreate(request)
    +getPaymentMethodUpdate(request)
    +paymentMethodUpdate(request)
    +paymentMethodDelete(request)
}

class ReviewController {
    +getAllReviewPage()
    +getCreateReviewOrViewReviewPage(request)
    +createReview(request)
    +updateReview(request)
}
class TenantController {
    +getAllTenantBoarding(request)
    +getDetailTenantBoarding(request)
    +getRequestTenant(request)
    +RequestTenant(request)
    +acceptTenant(tenantId)
    +getEndRentBoarding(request)
    +endRentBoarding(request)
}
class TransactionTypeController {
    +getAllTransactionTypePage(request)
    +getTransactionTypeCreate()
    +transactionTypeCreate(request)
    +getTransactionTypeUpdate(request)
    +TransactionTypeUpdate(request)
    +TransactionTypeDelete(request)
}
class UserController {
    +getProfilePage()
    +updateProfile(request)
    +getAllUserPage(request)
    +getUserDetail(request)
    +getUserUpdate(request)
    +UserUpdate(request)
    +UserDelete(request)
}
class WishlistController {
    +showWishlist()
    +addWishlist(request)
    +removeWishlist(request)
}

' Model
class Boarding {
    #BigInteger id
    #UnsignedBigInteger type_id
    #String boarding_name
    #LongText address
    #String latitude
    #String longitude
    #Integer rooms
    #Boolean shared_bathroom
    #Integer price
    #LongText boarding_desc
    #Datetime timestamps
}

class BoardingImage {
    #BigInteger id
    #UnsignedBigInteger boarding_id
    #String image
    #Datetime timestamps
}

class BoardingType {
    #BigInteger id
    #String boarding_type_name
    #Datetime timestamps
}

class Chat {
    #BigInteger id
    #UnsignedBigInteger sender_id
    #UnsignedBigInteger receiver_id
    #LongText message
    #Datetime timestamps
}

class Complain {
    #BigInteger id
    #UnsignedBigInteger user_id
    #UnsignedBigInteger boarding_id
    #UnsignedBigInteger complain_types
    #LongText complain_desc
    #LongText complain_image_url
    #Enumerate complain_status
}

class ComplainType {
    #BigInteger id
    #String complain_type_name
    #Datetime timestamps
}

class Facility {
    #BigInteger id
    #UnsignedBigInteger facility_id
    #UnsignedBigInteger boarding_id
    #Datetime timestamps
}

class FacilityDetail {
    #BigInteger id
    #String facility_detail_name
    #String facility_img_path
    #Datetime timestamps
}

class ManagerBoarding {
    #BigInteger id
    #UnsignedBigInteger user_id
    #UnsignedBigInteger boarding_id
    #Datetime timestamps
}

class OwnerBoarding {
    #BigInteger id
    #UnsignedBigInteger user_id
    #UnsignedBigInteger boarding_id
    #Enumerate owner_status
    #LongText declined_reason
    #Datetime timestamps
}

class PaymentMethod {
    #BigInteger id
    #String payment_method_name
    #Enumerate StateAttributeFontSize
    #Datetime timestamps
}

class RentTransaction {
    #BigInteger id
    #UnsignedBigInteger tenant_boarding_id
    #UnsignedBigInteger transaction_type_id
    #UnsignedBigInteger payment_method_id
    #UnsignedBigInteger invoice_id
    #Integer amount
    #Date payment_date
    #Enumerate payment_status
    #Enumerate payment_transferred_status
    #Boolean repeat_payment
    #Datetime timestamps
}

class Review {
    #BigInteger id
    #UnsignedBigInteger user_id
    #UnsignedBigInteger boarding_id
    #Integer rating
    #LongText review_desc
    #Datetime timestamps
}

class TenantBoarding {
    #BigInteger id
    #UnsignedBigInteger user_id
    #UnsignedBigInteger boarding_id
    #Date start_date
    #Date end_date
    #Enumerate tenant_status
    #LongText declined_reason
    #Datetime timestamps
}

class TransactionType {
    #BigInteger id
    #String transaction_type_name
    #Datetime timestamps
}

class User {
    #BigInteger id
    #String user_name
    #Enumerate gender
    #Enumerate user_status
    #String email
    #Datetime email_verified_at
    #String date_of_birth
    #String phone
    #Integer user_role_id
    #String profile_picture
    #String password
    #String bank_name
    #String account_number
    #Datetime timestamps
}

class UserRole {
    #BigInteger id
    #String user_role_name
    #Datetime timestamps
}

class Wishlist {
    #BigInteger id
    #UnsignedBigInteger user_id
    #UnsignedBigInteger boarding_id
    #Datetime timestamps
}

' Relationship
User "1"--"1" AuthController
User "1"--"1" UserController
Boarding "1"--"1" BoardingController
BoardingImage "1"--"1" BoardingImageController
BoardingType "1"--"1" BoardingTypeController
FacilityDetail "1"--"1" FacilityController
Wishlist "1"--"1" WishlistController
Chat "1"--"1" ChatController
Complain "1"--"1" ComplainController
ComplainType "1"--"1" ComplainTypeController
PaymentMethod "1"--"1" PaymentMethodController
TransactionType "1"--"1" TransactionTypeController
Review "1"--"1" ReviewController
RentTransaction "1"--"1" PaymentController
TenantBoarding "1"--"1" TenantController


User "1"--"1" UserRole
User "1"--"1" OwnerBoarding
OwnerBoarding "1"--"1" Boarding

User "1"--"1" ManagerBoarding
ManagerBoarding "1"--"1" Boarding

User "1"--"1" TenantBoarding
TenantBoarding "1"--"1" Boarding

User "1"--"1" Chat

User "1"--"1" Complain

User "1" -- "1" Wishlist

User "1"--"1" RentTransaction

User "1"--"1" Review

Complain "1"--"1" ComplainType

Boarding "1"--"1" BoardingImage
Boarding "1"--"1" BoardingType

Boarding "1"--"1" Facility
Facility "1"--"1" FacilityDetail

RentTransaction "1"--"1" TransactionType

RentTransaction "1"--"1" PaymentMethod

Wishlist "1"--"1" Boarding

Complain "1"--"1" Boarding

PaymentController ..> ChatController : use storeSpecificChatMessage method
PaymentController ..> TenantController : use acceptTenant method
@enduml