@startuml
' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "users" as usr {
  *User_id: Integer<<PK>>
  --
  *Name : Varchar
  *Email : Varchar
  *DOB : Date
  *Phone : Varchar
  *User_Role_id : Integer <<FK>>
  *profile_picture : Varchar
  *created_at : Date
  *updated_at : Date
}

entity "User_Role" as usrl {
  *User_Role_id: Integer<<PK>>
  --
  *Role_Name : Varchar
  *created_at : Date
  *updated_at : Date
}

entity "Boarding_Type" as bht {
  *Type_id : Integer <<PK>>
  --
  *Name : Varchar
  *Description : Varchar
  *created_at : Date
  *updated_at : Date
}

entity "Boarding_House" as bh {
  *Boarding_House_id : Integer <<PK>>
  --
  *Name : Varchar
  *Address : Varchar
  *latitude : Varchar
  *longitude : Varchar
  *Type_id : Integer <<FK>>
  *Boarding_House_Image_id : Integer<<FK>>
  *Rooms : Integer
  *Shared_Bathroom : Boolean
  *Price : Integer
  *Description : Varchar
  *Declined_Reason : Varchar
  *created_at : Date
  *updated_at : Date
}

entity "Facility_Detail" as fd {
  *Facility_Detail_Id: Integer <<FK>>
  --
  *Name : Varchar
  *Description : Varchar
  *created_at : Date
  *updated_at : Date
}

entity "Facility" as f {
  *Facility_id : Integer <<PK FK>>
  *Boarding_id : Integer <<PK FK>>
  --
  *created_at : Date
  *updated_at : Date
}

entity "boarding_images" as bhi {
  *Boarding_House_Img_id : Integer <<PK>>
  --
  *Image : image
  *created_at : Date
  *updated_at : Date
}

entity "Rent_Transaction_Header" as rt {
  *Rent_Transaction_id : Integer <<PK>>
  --
  *User_id Integer <<FK>>
  *created_at : Date
  *updated_at : Date
  
}

entity "Rent_Transaction_Detail" as rtd {
  *RentTransaction_Detail_id : Integer <<PK>>
  --
  *Rent_Transaction_Header_id : Integer <<FK>> 
  *Boarding_House_id : Integer <<FK>>
  *Payment_Type_id : Integer <<FK>>
  *Start_Date : Date
  *End_Date : Date
  *payment_status : Boolean
  *Declined_Reason : Varchar
  *created_at : Date
  *updated_at : Date
}

entity "owner_boardings" as lobh {
  *list_owner_id : Integer <<PK>>
  --
  *User_id : Integer <<FK>>
  *Boarding_House_id : Integer <<FK>>
  *created_at : Date
  *updated_at : Date
}

entity "Review" as rvw {
  *Review_id : Integer <<PK>>
  --
  *User_id : Integer <<FK>>
  *Boarding_house_id : Integer <<FK>>
  *Rating : Integer
  *Description : Varchar
  *created_at : Date
  *updated_at : Date
}

entity "complains" as cmpln {
  *Complains_id : Integer <<PK>>
  --
  *User_id : Integer <<FK>>
  *Boarding_House_id : Integer <<FK>>
  *Complain_Type_id : Integer <<FK>>
  *Description : Varchar
  *created_at : Date
  *updated_at : Date
}

entity "complain_Types" as cmplnt {
  *Complain_Type_id : Integer <<PK>>
  --
  *Description : Varchar
}

entity "wishlists" as fr { 
  *Boarding_id: Integer<<PK FK>>
  *User_id: Integer<<PK FK>>
  --
  *created_at : Date
  *updated_at : Date
}

entity "payment_types" as pymnt {
  *Payment_id: Integer<<PK>>
  --
  *name: Varchar
  *created_at : Date
  *updated_at : Date
}

entity "Chat" as cht {
  *Chats_id: Integer<<PK>>
  --
  *User_FK: Integer<<FK>>
  *Chatroom_id: Integer<<FK>>
  *Message: Varchar
  *Is_Deleted: Boolean
  *IS_Edited: Boolean
  *created_at : Date
  *updated_at : Date
}

entity "Chatroom" as chtrm {
  *Chatsroom_id: Integer<<PK>>
  --
  *created_at : Date
  *updated_at : Date
}

usr ||..o{ usrl
bh ||..o{ bhi
bh ||..o{ f
fd ||..o{ f

usr ||..o{ rt
bh ||..o{ rtd
rt ||..{rtd
pymnt ||..o{ rtd

usr ||..o{ lobh
bh ||..o{ lobh

usr ||..o{ rvw
bh ||..o{ rvw

usr ||..o{ cmpln
bh ||..o{ cmpln
cmplnt ||..o{ cmpln

bht ||..o{ bh


usr ||..o{ fr
bh ||..o{ fr

usr |o..o{ cht
chtrm |o..o{ cht

@enduml


' https://plantuml.com/ie-diagram
' * Meaning
' optional attribute
'   **optional bold attribute
'   * mandatory bold attribute