@startuml
' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "users" as usr {
  *id: Integer<<PK>>
  --
  *user_name : Varchar
  *gender : Varchar
  *email : Varchar
  *email_verified_at : Varchar
  *date_of_birth : Date
  *phone : Varchar
  *user_role_id : Integer <<FK>>
  *profile_picture : Varchar
  *password : Varchar
  *created_at : Date
  *updated_at : Date
}

entity "user_roles" as usrl {
  *id: Integer<<PK>>
  --
  *user_role_name : Varchar
  *created_at : Date
  *updated_at : Date
}

entity "boarding_types" as bht {
  *id : Integer <<PK>>
  --
  *name : Varchar
  *created_at : Date
  *updated_at : Date
}

entity "boardings" as bh {
  *id : Integer <<PK>>
  --
  *boarding_name : Varchar
  *address : Varchar
  *latitude : Double
  *longitude : Double
  *type_id : Integer <<FK>>
  *rooms : Integer
  *shared_bathroom : Boolean
  *price : Integer
  *boarding_desc : Varchar
  *created_at : Date
  *updated_at : Date
}

entity "facility_details" as fd {
  *id: Integer <<FK>>
  --
  *name : Varchar
  *created_at : Date
  *updated_at : Date
}

' Composite key
entity "facilities" as f {
  *id : Integer <<PK>>
  *facility_id : Integer <<FK>>
  *boarding_id : Integer <<FK>>
  --
  *created_at : Date
  *updated_at : Date
}

entity "boarding_images" as bhi {
  *id : Integer <<PK>>
  *boarding_id : Integer <<FK>>
  --
  *image : image
  *created_at : Date
  *updated_at : Date
}

entity "rent_transaction_header" as rt {
  *id : Integer <<PK>>
  --
  *user_id : Integer <<FK>>
  *created_at : Date
  *updated_at : Date
  
}

entity "rent_transaction_detail" as rtd {
  *id : Integer <<PK>>
  --
  *transaction_header_id : Integer <<FK>> 
  *boarding_id : Integer <<FK>>
  *payment_type_id : Integer <<FK>>
  *start_date : Date
  *end_date : Date
  *payment_status : Boolean
  *declined_reason : Varchar
  *created_at : Date
  *updated_at : Date
}

' entity "boarding_status" as bhst{
'     *id : Integer <<PK>>
'     --
'     *name : Varchar
'     *created_at : Date
'     *updated_at : Date
' }

entity "tenant_boardings" as tenbh {
  *id : Integer <<PK>>
  --
  *user_id : Integer <<FK>>
  *boarding_id : Integer <<FK>>
  *status: Enumerate
  *declined_reason : Varchar
  *created_at : Date
  *updated_at : Date
}

entity "owner_boardings" as lobh {
  *id : Integer <<PK>>
  --
  *user_id : Integer <<FK>>
  *boarding_id : Integer <<FK>>
  *status: Enumerate
  *declined_reason : Varchar
  *created_at : Date
  *updated_at : Date
}

entity "manager_boardings" as mabh {
  *id : Integer <<PK>>
  --
  *owner_boarding_id : Integer <<FK>>
  *user_id : Integer <<FK>>
  *created_at : Date
  *updated_at : Date
}

entity "complain_types" as cmplnt {
  *id : Integer <<PK>>
  --
  *complain_type_name : Varchar
}

entity "reviews" as rvw {
  *id : Integer <<PK>>
  --
  *user_id : Integer <<FK>>
  *boarding_id : Integer <<FK>>
  *rating : Integer
  *review_desc : Varchar
  *created_at : Date
  *updated_at : Date
}

entity "complains" as cmpln {
  *id : Integer <<PK>>
  --
  *user_id : Integer <<FK>>
  *boarding_id : Integer <<FK>>
  *complain_type_id : Integer <<FK>>
  *complain_desc : Varchar
  *created_at : Date
  *updated_at : Date
}

' Composite key
entity "wishlists" as fr {
  *id: Integer <<PK>>
  *boarding_id: Integer<<FK>>
  *user_id: Integer<<FK>>
  --
  *created_at : Date
  *updated_at : Date
}

entity "payment_types" as pymnt {
  *id: Integer<<PK>>
  --
  *payment_type_name: Varchar
  *created_at : Date
  *updated_at : Date
}

entity "chats" as cht {
  *id: Integer<<PK>>
  --
  *user_id: Integer<<FK>>
  *chatroom_id: Integer<<FK>>
  *message: Varchar
  *is_deleted: Boolean
  *is_edited: Boolean
  *created_at : Date
  *updated_at : Date
}

entity "chatrooms" as chtrm {
  *id: Integer<<PK>>
  --
  *created_at : Date
  *updated_at : Date
}

usrl ||..o{usr
bh ||..o{ bhi
bh ||..o{ f
fd ||..o{ f

usr ||..o{ rt
bh ||..o{ rtd
rt ||..||rtd
pymnt ||..o{ rtd

usr ||..o{ lobh
bh ||..o{ lobh

usr ||..o{ tenbh
bh ||..o{ tenbh

usr ||..o{ mabh
lobh ||..o{ mabh

usr ||..o{ rvw
bh ||..o{ rvw

usr ||..o{ cmpln
bh ||..o{ cmpln
cmplnt ||..o{ cmpln

bht ||..o{ bh


usr ||..o{ fr
bh ||..o{ fr

usr |o..o{ cht
chtrm |o..o{ cht

@enduml


' https://plantuml.com/ie-diagram
' * Meaning
' optional attribute
'   **optional bold attribute
'   * mandatory bold attribute