@startuml
' Controller
class AuthController {
    getRegisterPage()
    getLoginPage()
    register()
    login()
    logout()
}

class BoardingController {
    getMainPage()
    indexAdmin()
    indexManager()
    indexOwner()
    indexTenant()
    getAllBoardingHouse()
    getBoardingHouseDetail()
    searchBoardingByLocation()
    getCreateOwnerBoarding()
    createOwnerBoarding()
    getReadBoarding()
    getReadingBoardingTenant()
    getUpdateBoarding()
    updateBoarding()
    deleteBoarding()
    boardingRent()
    getAdminApproveBoarding()
    adminApproveBoarding()
    getReapproveBoarding()
    reapproveBoarding()
    disableBoardingOwner()
    enableBoardingOwner()
}

class BoardingImageController {
    deleteImage()
}

class BoardingTypeController {
    getAllBoardingTypePage()
    getBoardingTypeCreate()
    boardingTypeCreate()
    getBoardingTypeUpdate()
    boardingTypeUpdate()
    boardingTypeDelete()
}

class ChatController {
    getChatPage()
    getChatMessage()
    storeChatMessage()
    storeSpecificChatMessage()
}

class ComplainController {
    getComplainListPage()
    getCreateComplainPage()
    createComplain()
    getComplainDetail()
    setComplainStatus()
    getOwnerComplainPage()
    getSelectedBoardingHouseComplainList()
}

class ComplainTypeController {
    getAllComplainTypePage()
    getComplainTypeCreate()
    complainTypeCreate()
    getComplainTypeUpdate()
    complainTypeUpdate()
    complainTypeDelete()
}

class FacilityController {
    getAllFacilitypage()
    getFacilityCreate()
    facilityCreate()
    getFacilityUpdate()
    facilityUpdate()
    facilityDelete()
}
class PaymentController {
    addPaymentTenant()
    addPaymentManager()
    getPaymentPageManager()
    getCheckInvoiceRequest()
    getInvoiceListProcessing()
    getBoardingHouseName()
    getTransactionTypeName()
    getAllTenants()
    getTenantBoarding()
    getTenantIdByEmail()
    getAllPayment()
    getListPaymentByUser()
    getListPaymentByBoardingId()
    getTenantById()
    getInvoiceDetail()
    getEditPayment()
    getPaymentPageTenant()
    getPaymentRemit()
    getPaymentSupport()
    cancelPayment()
    updateInvoiceStatus()
    updatePayment()
    updateTransferredStatus()
    generateInvoice()
    schedulePayment()
    checkLatePayment()
}

class PaymentMethodController {
    getAllPaymentMethodPage()
    getPaymentMethodCreate()
    paymentMethodCreate()
    getPaymentMethodUpdate()
    paymentMethodUpdate()
    paymentMethodDelete()
}

class ReviewController {
    getAllReviewPage()
    getCreateReviewOrViewReviewPage()
    createReview()
    updateReview()
}
class TenantController {
    getAllTenantBoarding()
    getDetailTenantBoarding()
    getRequestTenant()
    RequestTenant()
    getEndRentBoarding()
    endRentBoarding()
}
class TransactionTypeController {
    getAllTransactionTypePage()
    getTransactionTypeCreate()
    transactionTypeCreate()
    getTransactionTypeUpdate()
    TransactionTypeUpdate()
    TransactionTypeDelete()
}
class UserController {
    getProfilePage()
    updateProfile()
    getAllUserPage()
    getUserDetail()
    getUserUpdate()
    UserUpdate()
    UserDelete()
}
class WishlistController {
    showWishlist()
    addWishlist()
    removeWishlist()
}


' Model
class BoardingModel {
    BigInteger id
    UnsignedBigInteger type_id
    String boarding_name
    LongText address
    String latitude
    String longitude
    Integer rooms
    Boolean shared_bathroom
    Integer price
    LongText boarding_desc
    Datetime timestamps
}

class BoardingImageModel {
    BigInteger id
    UnsignedBigInteger boarding_id
    String image
    Datetime timestamps
}

class BoardingTypeModel {
    BigInteger id
    String boarding_type_name
    Datetime timestamps
}

class ChatModel {
    BigInteger id
    UnsignedBigInteger sender_id
    UnsignedBigInteger receiver_id
    LongText message
    Datetime timestamps
}

class ComplainModel {
    BigInteger id
    UnsignedBigInteger user_id
    UnsignedBigInteger boarding_id
    UnsignedBigInteger complain_types
    LongText complain_desc
    LongText complain_image_url
    Enumerate complain_status
}

class ComplainTypeModel {
    BigInteger id
    String complain_type_name
    Datetime timestamps
}

class FacilityModel {
    BigInteger id
    UnsignedBigInteger facility_id
    UnsignedBigInteger boarding_id
    Datetime timestamps
}

class FacilityDetailModel {
    BigInteger id
    String facility_detail_name
    String facility_img_path
    Datetime timestamps
}

class ManagerBoardingModel {
    BigInteger id
    UnsignedBigInteger user_id
    UnsignedBigInteger boarding_id
    Datetime timestamps
}

class OwnerBoardingModel {
    BigInteger id
    UnsignedBigInteger user_id
    UnsignedBigInteger boarding_id
    Enumerate owner_status
    LongText declined_reason
    Datetime timestamps
}

class PaymentMethodModel {
    BigInteger id
    String payment_method_name
    Enumerate StateAttributeFontSize
    Datetime timestamps
}

class RentTransactionModel {
    BigInteger id
    UnsignedBigInteger tenant_boarding_id
    UnsignedBigInteger transaction_type_id
    UnsignedBigInteger payment_method_id
    UnsignedBigInteger invoice_id
    Integer amount
    Date payment_date
    Enumerate payment_status
    Enumerate payment_transferred_status
    Boolean repeat_payment
    Datetime timestamps
}

class ReviewModel {
    BigInteger id
    UnsignedBigInteger user_id
    UnsignedBigInteger boarding_id
    Integer rating
    LongText review_desc
    Datetime timestamps
}

class TenantBoardingModel {
    BigInteger id
    UnsignedBigInteger user_id
    UnsignedBigInteger boarding_id
    Date start_date
    Date end_date
    Enumerate tenant_status
    LongText declined_reason
    Datetime timestamps
}

class TransactionTypeModel {
    BigInteger id
    String transaction_type_name
    Datetime timestamps
}

class UserModel {
    BigInteger id
    String user_name
    Enumerate gender
    Enumerate user_status
    String email
    Datetime email_verified_at
    String date_of_birth
    String phone
    Integer user_role_id
    String profile_picture
    String password
    String bank_name
    String account_number
    Datetime timestamps
}

class UserRoleModel {
    BigInteger id
    String user_role_name
    Datetime timestamps
}

class WishlistModel {
    BigInteger id
    UnsignedBigInteger user_id
    UnsignedBigInteger boarding_id
    Datetime timestamps
}

' View
class LoginView {}

class RegisterView{}

class AdminApproveBoardingView {}

class AllBoardingHouseView {}

class BoardingManagementAdminView {}

class BoardingManagementOwnerView {}

class BoardingManagementTenantView {}

class CreateBoardingView {}

class EndBoardingRentView {}

class ReadBoardingView {}

class ReapproveBoardingView {}

class SearchBoardingResultView {}

class SelectedBoardingHouseView {}

class UpdateBoardingView {}

class CreateBoardingTypeView {}

class ListBoardingTypeView {}

class UpdateBoardingTypeView {}

class OwnerBoardingHouseListView {}

class SelectedBoardingHouseComplainListView {}

class ComplainDetailView {}

class ComplainListView {}

class CreateComplainView {}

class CreateComplainTypeView {}

class ListComplainTypeView {}

class UpdateComplainTypeView {}

class CreateFacilityView {}

class ListFacilityView {}

class UpdateFacilityView {}

class PaymentCheckInvoiceView {}

class PaymentHistoryView {}

class PaymentPageManagerView {}

class PaymentPageTenantView {}

class PaymentRemitView {}

class PaymentSupportView {}

class CreatePaymentMethodView {}

class ListPaymentMethodView {}

class UpdatePaymentMethodView {}

class AllReviewView {}

class CreateOrViewReviewView {}

class ReadTenantView {}

class RequestTenantView {}

class TenantListView {}

class CreateTransactionTypeView {}

class ListTransactionTypeView {}

class UpdateTransactionTypeView {}

class ListUserView {}

class ReadUserView {}

class UpdateUserView {}

class ChatView {}

class EditProfileView {}

class MainPageView {}

class WishlistView {}

' Middleware
class Middleware {}

Middleware "1"--"1" BoardingController
Middleware "1"--"1" BoardingImageController
Middleware "1"--"1" BoardingTypeController
Middleware "1"--"1" ChatController
Middleware "1"--"1" ComplainController
Middleware "1"--"1" ComplainTypeController
Middleware "1"--"1" FacilityController
Middleware "1"--"1" PaymentController
Middleware "1"--"1" PaymentMethodController
Middleware "1"--"1" ReviewController
Middleware "1"--"1" TenantController
Middleware "1"--"1" TransactionTypeController
Middleware "1"--"1" UserController
Middleware "1"--"1" WishlistController
Middleware "1"--"1" AuthController

BoardingController "1"--"1" MainPageView
BoardingController "1"--"1" BoardingManagementAdminView
BoardingController "1"--"1" BoardingManagementManagerView
BoardingController "1"--"1" BoardingManagementOwnerView
BoardingController "1"--"1" BoardingManagementTenantView
BoardingController "1"--"1" AllBoardingHouseView
BoardingController "1"--"1" SelectedBoardingHouseView
BoardingController "1"--"1" SearchBoardingResultView
BoardingController "1"--"1" ReadBoardingView
BoardingController "1"--"1" UpdateBoardingView
BoardingController "1"--"1" AdminApproveBoardingView
BoardingController "1"--"1" ReapproveBoardingView
BoardingController "1"--"1" CreateBoardingView

BoardingTypeController "1"--"1" ListBoardingTypeView
BoardingTypeController "1"--"1" CreateBoardingTypeView
BoardingTypeController "1"--"1" UpdateBoardingTypeView

ChatController "1"--"1" ChatView

ComplainController "1"--"1" ComplainListView
ComplainController "1"--"1" CreateComplainView
ComplainController "1"--"1" ComplainDetailView
ComplainController "1"--"1" OwnerBoardingHouseListView
ComplainController "1"--"1" SelectedBoardingHouseComplainListView

ComplainTypeController "1"--"1" ListComplainTypeView
ComplainTypeController "1"--"1" CreateComplainTypeView
ComplainTypeController "1"--"1" UpdateComplainTypeView

FacilityController "1"--"1" ListFacilityView
FacilityController "1"--"1" CreateFacilityView
FacilityController "1"--"1" UpdateFacilityView

PaymentController "1"--"1" PaymentPageManagerView
PaymentController "1"--"1" PaymentCheckInvoiceView
PaymentController "1"--"1" PaymentHistoryView
PaymentController "1"--"1" PaymentPageManagerView
PaymentController "1"--"1" PaymentPageTenantView
PaymentController "1"--"1" PaymentRemitView
PaymentController "1"--"1" PaymentSupportView

PaymentMethodController "1"--"1" ListPaymentMethodView
PaymentMethodController "1"--"1" CreatePaymentMethodView
PaymentMethodController "1"--"1" UpdatePaymentMethodView

ReviewController "1"--"1" AllReviewView
ReviewController "1"--"1" CreateOrViewReviewView

TenantController "1"--"1" TenantListView
TenantController "1"--"1" ReadTenantView
TenantController "1"--"1" RequestTenantView
TenantController "1"--"1" EndBoardingRentView

TransactionTypeController "1"--"1" ListTransactionTypeView
TransactionTypeController "1"--"1" CreateTransactionTypeView
TransactionTypeController "1"--"1" UpdateTransactionTypeView

UserController "1"--"1" EditProfileView
UserController "1"--"1" ListUserView
UserController "1"--"1" ReadUserView
UserController "1"--"1" UpdateUserView

WishlistController "1"--"1" WishlistView

AuthController "1"--"1" LoginView
AuthController "1"--"1" RegisterView


ReviewModel "1"--"1" BoardingController
ReviewModel "1"--"1" ReviewController  

OwnerBoardingModel "1"--"1" BoardingController  
OwnerBoardingModel "1"--"1" BoardingController  
OwnerBoardingModel "1"--"1" ChatController  
OwnerBoardingModel "1"--"1" ComplainController
OwnerBoardingModel "1"--"1" PaymentController
OwnerBoardingModel "1"--"1" TenantController

UserModel "1"--"1" AuthController
UserModel "1"--"1" BoardingController
UserModel "1"--"1" ChatController
UserModel "1"--"1" ComplainController
UserModel "1"--"1" PaymentController
UserModel "1"--"1" TenantController
UserModel "1"--"1" UserController

userRoleModel "1"--"1" AuthController
UserRoleModel "1"--"1" UserController

BoardingModel "1"--"1" BoardingController
BoardingModel "1"--"1" ComplainController
BoardingModel "1"--"1" PaymentController
BoardingModel "1"--"1" ReviewController
BoardingModel "1"--"1" TenantController
BoardingModel "1"--"1" WishlistController

BoardingImageModel "1"--"1" BoardingController
BoardingImageModel "1"--"1" BoardingImageController
BoardingImageModel "1"--"1" WishlistController

BoardingTypeModel "1"--"1" BoardingController
BoardingTypeModel "1"--"1" BoardingTypeController


ManagerBoardingModel "1"--"1" BoardingController
ManagerBoardingModel "1"--"1" ChatController
ManagerBoardingModel "1"--"1" ComplainController
ManagerBoardingModel "1"--"1" PaymentController
ManagerBoardingModel "1"--"1" TenantController

TenantBoardingModel "1"--"1" BoardingController
TenantBoardingModel "1"--"1" ChatController
TenantBoardingModel "1"--"1" ComplainController
TenantBoardingModel "1"--"1" PaymentController
TenantBoardingModel "1"--"1" ReviewController
TenantBoardingModel "1"--"1" TenantController

FacilityModel "1"--"1" BoardingController

FacilityDetailModel "1"--"1" BoardingController
FacilityDetailModel "1"--"1" FacilityController

WishlistModel "1"--"1" BoardingController
WishlistModel "1"--"1" WishlistController

ChatModel "1"--"1" TenantController
ChatModel "1"--"1" ChatController

ComplainModel "1"--"1" ComplainController

ComplainTypeModel "1"--"1" ComplainController
ComplainTypeModel "1"--"1" ComplainTypeController

PaymentMethodModel "1"--"1" PaymentController
PaymentMethodModel "1"--"1" PaymentMethodController

RentTransactionModel "1"--"1" PaymentController

TransactionTypeModel "1"--"1" PaymentController
TransactionTypeModel "1"--"1" TransactionTypeController

@enduml