@startuml
actor Admin as act
participant DeleteComplainTypeConfirmationPage as view
participant ComplainTypeController as ctrl
participant ComplainTypeModel as model

act -> view : getDeleteComplainTypeConfirmationPage()
act <-- view : displayDeleteComplainTypeConfirmationPage()

    act->view : inputDeleteComplainTypeConfirmationForm()
    alt Confirm
        view->ctrl: deleteComplainType(id)
        ctrl->model: deleteComplainType(id)
        model --> ctrl: success_response
        ctrl --> view: success_response
        view-->act: displayAllComplainTypePage(success_response)
    else Back
        view-->act: displayAllComplainTypePage()
    end

@enduml
