@startuml
title Add Complain Type
actor Admin as act
participant AddComplainTypePage as view
participant ComplainController as ctrl
participant ComplainModel as model

act -> view : getAddComplainTypePage()
act <-- view : displayAddComplainTypePage()

    act->view : inputAddComplainTypeForm()
    view->ctrl : validateComplainTypeData(complain_type_data)
        alt Valid
        ctrl-->view:input_validated_response
        view->ctrl: addComplainType(complain_type_data)
        ctrl->model: addComplainType(complain_type_data)
        model --> ctrl: success_response
        ctrl --> view: success_response
        view-->act: displayAllComplainTypePage(success_response)
        else Not Valid
        ctrl --> view: error_response
        view-->act: getAddComplainTypePage(error_response)
        end


@enduml
