@startuml
title View All Complain Type
actor Admin as act
participant ViewAllComplainTypesPage as view
participant ComplainTypesController as ctrl
participant ComplainTypesModel as model

act -> view: openAllComplainTypesPage()
view -> ctrl: getAllComplainTypes()
ctrl -> model: getAllComplainTypesFromDB()
ctrl <-- model: all_complain_types
view <-- ctrl: all_complain_types
act <-- view: displayAllComplainTypesPage(all_complain_types)

@enduml