@startuml
actor Admin as act
participant UpdateComplainTypePage as view
participant ComplainTypeController as ctrl
participant ComplainTypeModel as model

act -> view : openUpdateComplainTypePage()
view -> ctrl : getUpdateComplainTypePage(complain_type_id)
ctrl -> model : updateComplainTypePageGet(complain_type_id)
model --> ctrl : complain_type_data
ctrl --> view : complain_type_data
view --> act : displayUpdateComplainTypePage(complain_type_data)

    act->view : inputUpdateComplainTypeForm(complain_type_data)
    view->ctrl : validateComplainTypeData(complain_type_data)
        alt Valid
        ctrl-->view:input_validated_response
        view->ctrl: updateComplainType(complain_type_data)
        ctrl->model: updateComplainType(complain_type_data)
        model --> ctrl: success_response
        ctrl --> view: success_response
        view-->act: displayAllComplainTypesPage(success_response)
        else Not Valid
        ctrl --> view: error_response
        view-->act: getUpdateComplainTypePage(error_response)
        end


@enduml
