@startuml
actor Admin as act
participant UpdateUserPage as view
participant UserController as ctrl
participant UserModel as model

act -> view : openUpdateUserPage()
view -> ctrl : getUpdateUserPage(user_id)
ctrl -> model : updateUserPageGet(user_id)
model --> ctrl : user_data
ctrl --> view : user_data
view --> act : displayUpdateUserPage(user_data)

    act->view : inputUpdateUserForm(user_data)
    view->ctrl : validateUserData(user_data)
        alt Valid
        ctrl-->view:input_validated_response
        view->ctrl: updateUser(user_data)
        ctrl->model: updateUser(user_data)
        model --> ctrl: success_response
        ctrl --> view: success_response
        view-->act: displayAllUsersPage(success_response)
        else Not Valid
        ctrl --> view: error_response
        view-->act: getUpdateUserPage(error_response)
        end


@enduml
