@startuml
title View Current Users
actor Admin as act
participant CurrentUserPage as view
participant UserController as ctrl
participant UserModel as model

act -> view: openCurrentUsersPage()
view -> ctrl: getCurrentUsers()
ctrl -> model: getCurrentUsersFromDB()
ctrl <-- model: current_user
view <-- ctrl: current_user
act <-- view: displayCurrentUserPage(current_user)

@enduml