@startuml
actor Admin as act
participant ViewAllUserPage as view
participant UserController as ctrl
participant UserModel as model

act -> view: openAllUsersPage()
view -> ctrl: getAllUsers()
ctrl -> model: getAllUsersFromDB()
ctrl <-- model: all_users
view <-- ctrl: all_users
act <-- view: displayAllUsersPage(all_users)

@enduml