@startuml
actor Admin as act
participant DeleteUserConfirmationPage as view
participant UserController as ctrl
participant UserModel as model

act -> view : getDeleteUserConfirmationPage()
act <-- view : displayDeleteUserConfirmationPage()

    act->view : inputDeleteUserConfirmationForm()
    alt Confirm
        view->ctrl: deleteUser(id)
        ctrl->model: deleteUser(id)
        model --> ctrl: success_response
        ctrl --> view: success_response
        view-->act: displayAllUsersAdminPage(success_response)
    else Back
        view-->act: displayAllUserAdminPage()
    end

@enduml
