@startuml
Tenant -> BoardingHousePage: openAllBoardingHousePage()
BoardingHousePage -> BoardingController: getAllBoardingHouse()
BoardingController -> BoardingModel: getAllBoardingHouseData()
BoardingController <-- BoardingModel: boarding_houses_data
BoardingHousePage <-- BoardingController: boarding_houses_data
Tenant <-- BoardingHousePage: displayAllBoardingHousesPage(boarding_houses_data)

Tenant -> BoardingHousePage: openSelectedBoardingHouseDetail()
BoardingHousePage -> BoardingController: getSelectedBoardingHouseDetail()
BoardingController -> BoardingModel: selectedBoardingHouseDetailGet()
BoardingController <-- BoardingModel: boarding_house_detail_data
BoardingHousePage <-- BoardingController: boarding_house_detail_data
Tenant <-- BoardingHousePage: displaySelectedBoardingHouseDetailPage(boarding_house_detail_data)

Tenant -> BoardingHousePage: addToWishlist()
BoardingHousePage -> WishlistController: addToWishlist(Tenant_details, boarding_details)
WishlistController -> WishlistModel: insertIntoTenantWishlist(Tenant_details, boarding_details)
WishlistController <-- WishlistModel: success_response
BoardingHousePage <-- WishlistController: success_response
Tenant <-- BoardingHousePage: displaySelectedBoardingHouseDetailPage(boarding_house_detail_data, wishlist_response)

@enduml