@startuml
User -> BoardingHousePage: openAllBoardingHousePage()
BoardingHousePage -> BoardingController: getAllBoardingHouse()
BoardingController -> BoardingModel: getAllBoardingHouseData()
BoardingController <-- BoardingModel: boarding_houses_data
BoardingHousePage <-- BoardingController: boarding_houses_data
User <-- BoardingHousePage: displayAllBoardingHousesPage(boarding_houses_data)

User -> BoardingHousePage: openSelectedBoardingHouseDetail()
BoardingHousePage -> BoardingController: getSelectedBoardingHouseDetail()
BoardingController -> BoardingModel: selectedBoardingHouseDetailGet()
BoardingController <-- BoardingModel: boarding_house_detail_data
BoardingHousePage <-- BoardingController: boarding_house_detail_data
User <-- BoardingHousePage: displaySelectedBoardingHouseDetailPage(boarding_house_detail_data)

User -> BoardingHousePage: addToWishlist()
BoardingHousePage -> WishlistController: addToWishlist(user_details, boarding_details)
WishlistController -> WishlistModel: insertIntoUserWishlist(user_details, boarding_details)
WishlistController <-- WishlistModel: success_response
BoardingHousePage <-- WishlistController: success_response
User <-- BoardingHousePage: displaySelectedBoardingHouseDetailPage(boarding_house_detail_data, wishlist_response)

@enduml