@startuml
actor Admin as own
participant ":ViewAllBoardingHouse\n<<UI>>" as view
participant Controller as ctrl
participant Database as db

own -> view : View Selected Boarding House
view -> ctrl : Request Boarding House Details
ctrl -> db : Get Boarding House Details
ctrl <-- db : Return Boarding House Details
view <-- ctrl : Return Boarding House Details

    own->view : Delete Boarding House
    view->ctrl : Request Delete New Boarding House
    ctrl->db : Delete Selected Boarding House
    db-->ctrl: Return Success Message
    ctrl-->view: Return Success Message
    view-->own: Show Success Message

@enduml
