@startuml

User -> BoardingHousePage: openAllBoardingHousePage()
BoardingHousePage -> BoardingController: getAllBoardingHouse()
BoardingController -> BoardingModel: getAllBoardingHouseData()
BoardingController <-- BoardingModel: boarding_houses_data
BoardingHousePage <-- BoardingController: boarding_houses_data
User <-- BoardingHousePage: displayAllBoardingHousesPage(boarding_houses_data)

@enduml
