@startuml
User -> ChatPage: getChatPage()
ChatPage -> ChatController: getUserChatDetails(user_details);
ChatController -> ChatModel: getUserChatDetails(user_details);
ChatController <-- ChatModel: user_chat_details
ChatPage <-- ChatController: user_chat_details
User <-- ChatPage: displayChatPage(user_chat_details)
User -> ChatPage: chooseOneSpecificChat
User <-- ChatPage: displaySpecificChat()
opt New Message
    User -> ChatPage: sendMessage()
    ChatPage -> ChatController: saveUserMessageHistory(user_message)
    ChatController -> ChatModel: saveMessage(user_message)
    ChatController <-- ChatModel: new_message
    ChatPage <-- ChatController: new_message
    User <-- ChatPage: displaySpecificChat(new_message)
end
@enduml