@startuml
title ini kyknya duplicate complain change status deh
Manager -> ComplainListPage: requestSelectedBoardingHouseComplainList()
ComplainListPage -> ComplainController: requestSelectedBoardingHouseComplainList()
ComplainController -> ComplainModel: getSelectedBoardingHouseComplainList()
ComplainController <-- ComplainModel: complain_list
ComplainListPage <-- ComplainController: complain_list
Manager <-- ComplainListPage: showSelectedBoardingHouseComplainList(complain_list)
opt Update Status

    Manager -> ComplainListPage: selectComplain()
    ComplainListPage -> ComplainController: getComplainDetails(selected_complain)
    ComplainController -> ComplainModel: getComplainDetails(selected_complain)
    ComplainController <-- ComplainModel: selected_complain_detail
    ComplainListPage <-- ComplainController: selected_complain_detail
    Manager <-- ComplainListPage: showSelectedComplainDetail(complain_detail)

    Manager -> ComplainListPage: updateComplainStatus()
    ComplainListPage -> ComplainController: updateComplainStatus()
    ComplainController -> ComplainModel: updateComplainStatus()
    ComplainController <-- ComplainModel: success_response
    ComplainListPage <-- ComplainController: success_response
    Manager <-- ComplainListPage: redirectShowSelectedBoardingHouseComplainList(complain_list)
end
@enduml