@startuml
Manager -> ComplainListPage: getComplainListPage()
ComplainListPage -> ComplainController: getComplainList()
ComplainController -> ComplainModel: complainListGet()
ComplainController <-- ComplainModel: complainL_lst
ComplainListPage <-- ComplainController: complain_list
Manager <-- ComplainListPage: displayComplainListPage(complain_list)
opt Update Complain Status

    Manager -> ComplainListPage: Click Specific Complain
    ComplainListPage -> ComplainController: getComplainDetail(id) 
    ComplainController -> ComplainModel: complainDetailGet(id)
    ComplainController <-- ComplainModel: complain_detail 
    ComplainListPage <-- ComplainController: complain_detail 
    Manager <-- ComplainListPage: complainDetailPage(complain_detail)

    Manager -> ComplainListPage: updateComplainStatus()
    ComplainListPage -> ComplainController: updateComplainStatus()
    ComplainController -> ComplainModel: complainStatusUpdate()
    ComplainController <-- ComplainModel: success_message
    ComplainListPage <-- ComplainController: success_message
    Manager <-- ComplainListPage: redirectToComplainListPage()
end
@enduml