@startuml

Tenant -> WishlistPage: openWishlistPage()
WishlistPage -> WishlistController: getTenantWishlist(Tenant_details)
WishlistController -> WishlistModel: getTenantWishlistFromDB(Tenant_details)
WishlistController <-- WishlistModel: Tenant_wishlist_details
WishlistPage <-- WishlistController: Tenant_wishlist_details
Tenant <-- WishlistPage: displayWishlistPage(Tenant_wishlist_details)

Tenant -> WishlistPage: removeBoardingHouseFromWishlist()
WishlistPage -> WishlistController: deleteWishlistItem(boarding_details)
WishlistController -> WishlistModel: deleteWishlistItem(boarding_details)
WishlistController <-- WishlistModel: success_response
WishlistPage <-- WishlistController: success_response
Tenant <-- WishlistPage: displayWishlistPage(tenant_Wishlist_details)

@enduml