@startuml
User -> ProfilePage: getEditProfilePage()
ProfilePage -> UserController: getUserProfileDetails()
UserController -> UserModel: getUserProfileDetails()
UserController <-- UserModel: user_profile_details
ProfilePage <-- UserController: user_profile_details
User <-- ProfilePage: displayEditProfilePage(user_profile_details)
User -> ProfilePage: inputEditProfileForm()
ProfilePage -> UserController: validateUserInput(user_update_profile_input)
alt Validation Success
        UserController -> UserModel: updateUserDetails(user_update_profile_input)
        UserController <-- UserModel: success_response
        ProfilePage <-- UserController: success_response
        User <-- ProfilePage: displayHomePage()
else Validation Failed
        ProfilePage <-- UserController: failed_response
        User <-- ProfilePage: displayProfilePage(failed_response)
end
@enduml