@startuml
actor Admin as own
participant ":ViewAllFacilities\n<<UI>>" as view
participant Controller as ctrl
participant Database as db

own -> view : Request Show All Facilities (Admin) Page
view -> ctrl : Request Facility List
ctrl -> db : Get Facility List 
ctrl <-- db : Return Facility List
view <-- ctrl : Return Show All Facility (Admin) Page 

    alt User Click Add New Facility
    own->view : Add New Facility Details
    view->ctrl : Facility Validation (Add New)
        alt Validation Success
        ctrl->db : Add New Selected Facility Details
        db-->ctrl: Show Success Message
        ctrl-->view: Show Success Message
        else Validation Failed
        ctrl-->view: Show Failed Message
        end
    end

alt User View Specific Facility
own -> view : View Selected Facility
view -> ctrl : Request Facility Details
ctrl -> db : Get Facility Details
ctrl <-- db : Return Facility Details
view <-- ctrl : Return Facility Details
    alt User Click Delete Facility
    own->view : Delete Facility
    view->ctrl : Request Delete New Facility
    ctrl->db : Delete Selected Facility
    db-->ctrl: Show Success Message
    ctrl-->view: Show Success Message
    else User Click Update Facility
    own->view : Update Facility Detail
    view->ctrl : Facility Validation (Update)
        alt Validation Success
        ctrl->db : Update Selected Facility Details
        db-->ctrl: Show Success Message
        ctrl-->view: Show Success Message
        else Validation Failed
        ctrl-->view: Show Failed Message
        end
    end

@enduml
