@startuml

left to right direction
' top to bottom direction

title Facility Management (Admin)
partition User {
(*)  --> "Click on View All Facilities"
}
partition Website {
--> "Show All Facilities"
-->"Show Choices"
}
partition User {
--> "User Input Choice"
}
partition Website {
If "User Click" then

--> [Add] "Show Add New Facility Form"
}
partition User {
--> "User Fill in Add New facility Form"
}

partition Website {
--> "Show Add Confirmation"
}

partition User {
--> "User Click Add Confirmation"
}

partition Website {
    If "User Click" then
    --> [Yes] "Facility Validation (Add)"
        If "Is Facility Details Valid ?" then
        --> [Valid] "System Add New Facility"
        --> "Show Success Add New Facility Message"
        --> "Show All Facilities"
        else
        --> [Not Valid] "Show Failed Add New Facility Message"
        --> "Show Add New Facility Form"
        Endif
    else
    --> [No] "Show All Facilities"
    Endif

else
--> [Delete] "Delete Facility Form"
--> "Show Delete Confirmation"
}
partition User {
--> "User Click Delete Confirmation"
}
partition Website {
    If "User Click (Delete)" then
    --> [Yes] "System Delete Selected Facility"
    --> "Show Success Delete Facility Message"
    --> "Show All Facilities"
    else
    --> [No] "Show All Facilities"
    Endif

else
--> [Update] "Show Update Form"
}
partition User {
--> "User Update Facility Details"
}
partition Website {
--> "Show Update Confirmation"
}
partition User {
--> "User Click Update Confirmation"
}
partition Website {
    If "User Click" then
    --> [Yes] "Facility Validation (Update)"
        If "Is Facility Details Valid ?" then
        --> [Valid] "System Update Selected Facility"
        --> "Show Success Update Facility Message"
        --> "Show All Facilities"
        else
        --> [Not Valid] "Show Failed Update Facility Message"
        --> "Show Update Form"
        Endif
    else
    --> [No] "Show All Facilities"
    Endif
Endif
-->(*)
}
@enduml
