@startuml
User -> LoginPage: openLoginPage()
User <-- LoginPage: DisplayLoginPage()
User -> LoginPage: inputUserCredentials()
LoginPage -> AuthController: validateUserCredentials()
AuthController -> UserModel: requestUserDetail()

alt User Detail found
    AuthController <-- UserModel: user_details
    AuthController -> AuthController: authenticateUser()
    alt Authenticate Successful
       LoginPage <-- AuthController: validated_Login_response
       User <-- LoginPage: displayHomePage()
    else Authenticate Failed
       LoginPage <-- AuthController: invalidated_login_response
       User <-- LoginPage: displayLoginPageWithError()
    end
    
else User Detail not found
    AuthController <-- UserModel: user_not_found
    LoginPage <-- AuthController: fail_login_response
    User <-- LoginPage: displayLoginPageWithError()
end
@enduml