@startuml
title Make Complain
Tenant -> ComplainPage: getTenantComplainListPage()
ComplainPage -> ComplainController: getTenantComplainList()
ComplainController -> ComplainModel: getTenantComplainList()
ComplainController <-- ComplainModel: Tenant_complain_list
ComplainPage <-- ComplainController: Tenant_complain_list
Tenant <-- ComplainPage: displayTenantComplainListPage(Tenant_complain_list)
Tenant -> ComplainPage: getTenantNewComplainForm()
Tenant <-- ComplainPage: displayTenantComplainForm()
Tenant -> ComplainPage: inputTenantComplain()
ComplainPage -> ComplainController: insertNewComplainForm(Tenant_new_complain_details)
ComplainController -> ComplainModel: insertToDB(Tenant_new_complain_details)
ComplainController <-- ComplainModel: success_response
ComplainPage <-- ComplainController: success_response
Tenant <-- ComplainPage: displayTenantComplainlist()

@enduml