@startuml
User -> Website: Request Show Review Page
User <-- Website: Return Review Page
User -> Website: Insert Review, Give Rating
Website -> Controller: Validate User Input
Website <-- Controller: Send Success Response
Website -> Controller: Send Insert to DB Instructions
Controller -> Database: Insert to DB
Controller <-- Database: Show Success Insert to DB Response
Website <-- Controller: Return Insert Successful Message
User <-- Website: Show Home Page

@enduml