@startuml
title Make Review
Tenant -> ReviewPage: getReviewPage()
ReviewPage -> ReviewController: getReviewPage()
ReviewController -> ReviewModel: getReviewList(Tenant_details)
ReviewController <-- ReviewModel: review_list
ReviewPage <-- ReviewController: review_list
Tenant <-- ReviewPage: displayReviewPage(review_list)

Tenant -> ReviewPage: insertNewReview(review_details, rating)
ReviewPage -> ReviewController: validateTenantInput(review_details, rating)

alt (Tenant input valid)
    ReviewController -> ReviewModel: insertNewReview(review_details, rating)
    ReviewController <-- ReviewModel: success_response
    ReviewPage <-- ReviewController: success_response
    Tenant <-- ReviewPage: displayReviewPage()
else (Tenant input invalid)
    ReviewPage <-- ReviewController: failed_response
    Tenant <-- ReviewPage: displayReviewPage(failed_response)
end

@enduml