@startuml
User -> Website: Request Payment List Page
Website -> Controller: Request User Payment List Page
Controller -> Database: get user payment list
Controller <-- Database: return user payment list
Website <-- Database: return user payment list
User <-- Website: Return Payment List Page
User -> Website: Choose one of the payment
User <-- Website: Show Payment Details
User -> Website: Select Payment Method
Website -> Controller: Generate Payment
Website <-- Controller: return Generated payment data
User <-- Website: Show Generated payment data
User -> Website: Do the payment
Website -> Controller: check payment
alt Success
    Controller -> Database: Input User Payment History
    Controller <-- Database: Return Success Insert Response
    Website <-- Controller: Return Success Response
    User <-- Website: Show User Success Payment page
else Fail
    Website <-- Controller: Return Failed Response
    User <-- Website: Show User Failed Payment page
end
@enduml