@startuml
User -> Website: Request Payment List Page
Website -> Controller: Request User Payment List Page
Controller -> Database: get user payment list
Controller <-- Database: return user payment list
Website <-- Database: return user payment list
User <-- Website: Return Payment List Page
User -> Website: Choose one of the payment
User <-- Website: Show Payment Details
User -> Website: Select Payment Method
Website -> Controller: Request Upload Payment Receipt Page
Website <-- Controller: Return Upload Payment Receipt Page
User <-- Website: Show Upload Payment Receipt Page
User -> Website: Upload Payment Receipt
Website -> Controller: Request Database Insertion
Controller -> Database: Insert User Payment Receipt to Database
Controller <-- Database: Show Success Insertion
Website <-- Controller: Return Home Page
User <-- Website: Show Home Page
@enduml