@startuml
actor Owner as own
participant ":ViewAllPayments\n<<UI>>" as view
participant Controller as ctrl
participant Database as db

own -> view : Request Show All Payments (Owner) Page
view -> ctrl : Request Payment List Page
ctrl -> db : Get Payment List Page
ctrl <-- db : Return Payment List
view <-- ctrl : Return Show All Payment (Owner) Page 

@enduml
