@startuml
title Register
User -> RegisterPage: getRegistrationPage()
User <-- RegisterPage: displayRegistrationPage()
User -> RegisterPage: inputUserCredentials()
RegisterPage -> AuthController: validateUserCredentials(user_credentials)
alt Input Validated
    RegisterPage <-- AuthController: input_validated_response
    RegisterPage -> AuthController: insertToDB(user_credentials)
    AuthController -> UserModel: insertToDB(user_credentials)
    AuthController <-- UserModel: insert_success_response
    RegisterPage <-- AuthController: success_response
    User <-- RegisterPage: displayHomePage()
    
else Input Invalid
    RegisterPage <-- AuthController: error_response
    User <-- RegisterPage: displayRegisterPage(error_response)
end

@enduml