@startuml
Tenant -> ReviewPage: getReviewPage()
ReviewPage -> ReviewController: getReviewPage()
ReviewController -> ReviewModel: getReviewList(Tenant_details)
ReviewController <-- ReviewModel: review_list
ReviewPage <-- ReviewController: review_list
Tenant <-- ReviewPage: displayReviewPage(review_list)

alt (New Review)
    Tenant -> ReviewPage: insertNewReview(review_details, rating)
    ReviewPage -> ReviewController: validateTenantInput(review_details, rating)

    alt (Tenant input valid)
        ReviewController -> ReviewModel: insertNewReview(review_details, rating)
        ReviewController <-- ReviewModel: success_response
        ReviewPage <-- ReviewController: success_response
        Tenant <-- ReviewPage: displayReviewPage()
    else (Tenant input invalid)
        ReviewPage <-- ReviewController: failed_response
        Tenant <-- ReviewPage: displayReviewPage(failed_response)
    end

else (Update Old Review)
    Tenant -> ReviewPage: getSelectedTenantReviewDetails()
    ReviewPage -> ReviewController: getReviewDetails(selected_review_id)
    ReviewController -> ReviewModel: getReviewDetails(selected_review_id)
    ReviewController <-- ReviewModel: review_details
    ReviewPage <-- ReviewController: review_details
    Tenant <-- ReviewPage: displaySelectedTenantReviewDetails(review_details)

    Tenant -> ReviewPage: updateTenantReview()
    ReviewPage -> ReviewController: updateTenantReview(updated_review_details)
    ReviewController -> ReviewController: validateTenantReview(updated_review_details)

    alt (updated_review_details valid)
        ReviewController -> ReviewModel: updateTenantReview(updated_review_details)
        ReviewController <-- ReviewModel: success_response
        ReviewPage <-- ReviewController: success_response
        Tenant <-- ReviewPage: displayReviewPage()
    else (updated_review_details invalid)
        ReviewPage <-- ReviewController: failed_error_response
        Tenant <-- ReviewPage: displaySelectedTenantReviewDetails(failed_error_response)
    end
end

Tenant -> ReviewPage: Insert Review, Give Rating
ReviewPage -> ReviewController: Validate Tenant Input
ReviewPage <-- ReviewController: Send Success Response
ReviewPage -> ReviewController: Send Insert to DB Instructions
ReviewController -> ReviewModel: Insert to DB
ReviewController <-- ReviewModel: Show Success Insert to DB Response
ReviewPage <-- ReviewController: Return Insert Successful Message
Tenant <-- ReviewPage: Show Home Page

@enduml