@startuml
User -> SearchPage: inputSearchData()
SearchPage -> BoardingController: searchBoardingByLocation(searchData)
BoardingController -> BoardingModel: boardingGet(searchData)
alt result found
    BoardingController <-- BoardingModel: search_result
    SearchPage <-- BoardingController: search_result
    User <-- SearchPage: searchResultPage(search_result)
else result not found
    BoardingController <-- BoardingModel: empty
    SearchPage <-- BoardingController: empty
    User <-- SearchPage: searchResultEmptyPage()
end
@enduml
