@startuml
title Update Review
Tenant -> ReviewPage: openReviewPage()
ReviewPage -> ReviewController: getReviewPage(Tenant_data)
ReviewController -> ReviewModel: reviewPageGet(Tenant_data)
ReviewController <-- ReviewModel: review_data
ReviewPage <-- ReviewController: review_data
Tenant <-- ReviewPage: displayReviewPage(review_data)
Tenant -> ReviewPage: selectReview()
ReviewPage -> ReviewController: getReviewDetail()
ReviewController -> ReviewModel: reviewGetDetail()
ReviewController <-- ReviewModel: review_detail
ReviewPage <-- ReviewController: review_detail
Tenant <-- ReviewPage: reviewDetailPage(review_detail)
Tenant -> ReviewPage: updateReview(updated_review_data)
ReviewPage -> ReviewController: updateReview(updated_review_data)
ReviewController -> ReviewModel: reviewUpdate(updated_data)
ReviewController <-- ReviewModel: success_message
ReviewPage <-- ReviewController: success_message
Tenant <-- ReviewPage: redirectToReviewPage()
@enduml
