@startuml

User -> BoardingHouseManagementPage: openAllBoardingHouseManagementPage()
BoardingHouseManagementPage -> BoardingController: getAllBoardingHouse()
BoardingController -> BoardingModel: getAllBoardingHouseData()
BoardingController <-- BoardingModel: boarding_houses_data
BoardingHouseManagementPage <-- BoardingController: boarding_houses_data
User <-- BoardingHouseManagementPage: displayAllBoardingHousesPage(boarding_houses_data)

User -> BoardingHouseManagementPage: openSelectedBoardingHouseDetail()
BoardingHouseManagementPage -> BoardingController: getSelectedBoardingHouseDetail()
BoardingController -> BoardingModel: selectedBoardingHouseDetailGet()
BoardingController <-- BoardingModel: boarding_house_detail_data
BoardingHouseManagementPage <-- BoardingController: boarding_house_detail_data
User <-- BoardingHouseManagementPage: displaySelectedBoardingHouseDetailPage(boarding_house_detail_data)

@enduml
