@startuml
User -> ReviewPage: openReviewPage()
ReviewPage -> ReviewController: getReviewPage(user_data)
ReviewController -> ReviewModel: reviewPageGet(user_data)
ReviewController <-- ReviewModel: review_data
ReviewPage <-- ReviewController: review_data
User <-- ReviewPage: displayReviewPage(review_data)
@enduml
