@startuml
title View Boarding House Detail Management
User -> BoardingHouseDetailManagementPage: openSelectedBoardingHouseDetail()
BoardingHouseDetailManagementPage -> BoardingController: getSelectedBoardingHouseDetail()
BoardingController -> BoardingModel: selectedBoardingHouseDetailGet()
BoardingController <-- BoardingModel: boarding_house_detail_data
BoardingHouseDetailManagementPage <-- BoardingController: boarding_house_detail_data
User <-- BoardingHouseDetailManagementPage: displaySelectedBoardingHouseDetailPage(boarding_house_detail_data)

@enduml