@startuml
title View Complain
Tenant -> ComplainPage: getTenantComplainListPage()
ComplainPage -> ComplainController: getTenantComplainList()
ComplainController -> ComplainModel: getTenantComplainList()
ComplainController <-- ComplainModel: Tenant_complain_list
ComplainPage <-- ComplainController: Tenant_complain_list
Tenant <-- ComplainPage: displayTenantComplainListPage(Tenant_complain_list)
Tenant -> ComplainPage: getSpecificComplainDetails()
ComplainPage -> ComplainController: getSpecificComplainDetails()
ComplainController -> ComplainModel: getSpecificComplainDetails()
ComplainController <-- ComplainModel: specific_complain_details
ComplainPage <-- ComplainController: complain_details
Tenant <-- ComplainPage: displaySpecificComplainDetails(specific_complain_details)
@enduml