@startuml
actor "User" as act
participant ":PaymentDetail\n<<UI>>" as view
participant PaymentController as ctrl
participant TransactionModel as tm
participant Storage as stg
act -> view: getPaymentPage()
view -> ctrl: getPaymentDetail()
ctrl -> tm : getPaymentData(invoice_id)
ctrl <-- tm : payment_data
view <-- ctrl : payment_data
act <-- view : displayPaymentPage(payment_data) 
@enduml