@startuml

Tenant -> WishlistPage: openWishlistPage()
WishlistPage -> WishlistController: getTenantWishlist(Tenant_details)
WishlistController -> WishlistModel: getTenantWishlistFromDB(Tenant_details)
WishlistController <-- WishlistModel: Tenant_wishlist_details
WishlistPage <-- WishlistController: Tenant_wishlist_details
Tenant <-- WishlistPage: displayWishlistPage(Tenant_wishlist_details)

@enduml