@startuml
title View All Payment Methods 
|Admin|
start 
    :Admin Click See All Payment Methods;
|System|
    :System Retrieves All Payment Methods Data;
    :Show All Payment Methods Page;
    stop

@enduml