@startuml
title View All Boarding House Management
|Admin|
start 
    :Admin Click See All Boarding Houses Management;

|System|
    :System Retrieves All Boarding Houses Data;
    :Show All Boarding Houses Management Page;
    stop

@enduml