@startuml
title Boarding House Request
|Admin|
start 
    :Select Request Boarding House;
|System|
    : Show Request Boarding House Details;
|Admin|
    : Admin Click on Button;
|System|
switch ()
case (Approve)
    : Update Boarding House status to Approved;
    : Show Success Approving Boarding House Message;
case (Decline (Can Reapprove))
    : Update Boarding House to Declined;
    : Show Success Declining Boarding House (CanReapprove)  Message;
case (Decline (Cannot Reapprove))
    : Update Boarding House to Banned;
    : Show Success Declining Boarding House (Cannot Reapprove) Message;
endswitch
stop
@enduml