@startuml
title Ban Boarding House
|Admin|
start 
    :Select Delete/Ban Boarding House Button;
|System|
    :Show Delete/Ban Boarding House Confirmation;
|Admin|
    :Admin Click on Button;
    |System|
If () then (Confirm)
    : System Update Selected Boarding House status to Banned;
    : Show Success Deleting Boarding House Message;
else (Back)
    : Go Back to view All Boarding Management Page;  
endif
stop
@enduml