@startuml
title Filter Boarding House
|Auth User|
start 
    :Auth User Fill in Search Bar for Filter;

|System|
    :System Retrieves All Boarding Houses Data with Filter;
    :Show All Boarding Houses Page with Filter;
    stop

@enduml