@startuml
title Filter Boarding Types
|Admin|
start 
    :Admin Fill in Search Bar for Filter;
|System|
    :System Retrieves All Boarding Types Data with Filter;
    :Show All Boarding Types Page with Filter;
    stop

@enduml