@startuml
title Filter Complain Types
|Admin|
start 
    :Admin Fill in Search Bar for Filter;
|System|
    :System Retrieves All Complain Types Data with Filter;
    :Show All Complain Types Page with Filter;
    stop

@enduml