@startuml
title Filter Facility Details
|Admin|
start 
    :Admin Fill in Search Bar for Filter;
|System|
    :System Retrieves All Facility Details Data with Filter;
    :Show All Facility Details Page with Filter;
    stop

@enduml