@startuml
title Filter Payment Methods
|Admin|
start 
    :Admin Fill in Search Bar for Filter;
|System|
    :System Retrieves All Payment Methods Data with Filter;
    :Show All Payment Methods Page with Filter;
    stop

@enduml