@startuml
title Filter Tenants
|Manager|
start 
    :Manager Fill in Search Bar for Filter;
|System|
    :System Retrieves All Tenants Data with Filter;
    :Show All Tenants Page with Filter;
    stop

@enduml