@startuml
title Filter Transaction Type
|Admin|
start 
    :Admin Fill in Search Bar for Filter;
|System|
    :System Retrieves All Transaction Types Data with Filter;
    :Show All Transaction Types Page with Filter;
    stop

@enduml