@startuml
title Filter Users
|Admin|
start 
    :Admin Fill in Search Bar for Filter;
|System|
    :System Retrieves All Users Data with Filter;
    :Show All Users Page with Filter;
    stop

@enduml