@startuml
actor actin as act
participant ":PaymentSupport\n<<UI>>" as view
participant PaymentController as ctrl
participant TransactionModel as tm

act -> view: openSupportPaymentPage()
view -> ctrl: getSupportPaymentPage()
ctrl -> tm: getSupportPaymentData()
ctrl <-- tm: support_payment_data
view <-- ctrl: support_payment_data
act <-- view: displaySupportPayment(support_payment_data)

@enduml
