@startuml
title View Payment Remit
actor "Admin" as act
participant ":PaymentRemit\n<<UI>>" as view
participant PaymentController as ctrl
participant TransactionModel as tm

act -> view : openPaymentRemitPage()
view -> ctrl : getPaymentRemitPage()
ctrl -> tm : getProcessingTransaction()
ctrl <-- tm : transaction_data
view <-- ctrl : transaction_data
act <-- view : displayPaymentRemitPage(transaction_data)  