@startuml
title View Payment Invoice
actor "Admin" as act
participant ":CheckInvoiceRequest\n<<UI>>" as view
participant PaymentController as ctrl
participant TransactionModel as tm

act -> view : openCheckInvoicePage()
view -> ctrl : getCheckInvoicePage()
ctrl -> tm : getProcessingTransaction()
ctrl <-- tm : transaction_data
view <-- ctrl : transaction_data
act <-- view : displayCheckInvoicePage(transaction_data) 