@startuml
actor "Admin" as act
participant ":CheckInvoiceRequest\n<<UI>>" as view
participant PaymentController as pctrl
participant ChatController as cctrl
participant TransactionModel as tm
act -> view : openCheckInvoicePage()
view -> pctrl : getCheckInvoicePage()
pctrl -> tm : getProcessingTransaction()
pctrl <-- tm : transaction_data
view <-- ctrl : transaction_data
act <-- view : displayCheckInvoicePage(transaction_data) 