@startuml
title Boarding House View (Manager)
|Manager|
start 
    :Manager Click See All Boarding Houses;

|System|
    :System Retrieves All Boarding Houses Owned Data;
    :Show All Boarding Houses Owned Page (Manager);
    stop

@enduml