@startuml
title Disable Boarding House
|Owner|
start 
    :Select Disable Boarding House Button;
|System|
    :Show Disable Boarding House Confirmation;
|Owner|
    :Owner Click on Button;
    |System|
If () then (Confirm)
    : System Update Selected Boarding House status to Disable;
    : Show Success Disabling Boarding House Message;
else (Back)
    : Go Back to view All Boarding Management Page;  
endif
stop
@enduml