@startuml
title Enable Boarding House
|Admin|
start 
    :Select Enable Boarding House Button;
|System|
    :Show Enable Boarding House Confirmation;
|Admin|
    :Admin Click on Enable Button;
    |System|
    : System Update Selected Boarding House status to Approved;
    : Show Success Enabling Boarding House Message;
    : Go Back to view All Boarding Management Page;  

stop
@enduml