@startuml
title Tenant Request
|Manager/Owner|
    :Click Tenant Request Button;
|System|
    :Show Tenant Request Form;
|Manager/Owner|
    :Manager/Owner Click Button;
|System|
    If () then (Approve)
        :Update Tenant Request Status to Approved;
        :Check If Current Boarding Room became Full;
        If () then (Full)
        :Reject Other Tenant that have Requested to this Boarding;
        else (Not Full)
        endif

        :Check Tenant Pending Request;
        If () then (Exist)
        :Reject Tenant`s other Pending Request;
        else (Not Exist)
        endif
    :Show Success Accepting Message;
    else (Decline)
        :Update Tenant Request Status to Declined;
        :Show Success Declining Message;
    endif
stop

@enduml
