@startuml
title View All Tenant
|Manager|
start 
    :Manager Click See All Tenants;

|System|
    :System Retrieves All Tenants Owned Data;
    :Show All Tenants Owned Page (Manager);
    stop

@enduml