@startuml
title View Boarding House Own by Manager
|Manager|
start 
    :Manager Click View Tenant Detail;

|System|
    :System Retrieves Specifiv Tenant Detail Data;
    :Show Specifiv Tenant Detail Page (Manager);
    stop

@enduml