@startuml
title Add facility Detail
actor Admin as act
participant AddFacilityDetailPage as view
participant FacilityDetailController as ctrl
participant FacilityDetailModel as model

act -> view : getAddFacilityDetailPage()
act <-- view : displayAddFacilityDetailPage()

    act->view : inputAddFacilityDetailForm()
    view->ctrl : validateFacilityDetailData(facility_details_data)
        alt Valid
        ctrl-->view:input_validated_response
        view->ctrl: addFacilityDetail(facility_details_data)
        ctrl->model: addFacilityDetail(facility_details_data)
        model --> ctrl: success_response
        ctrl --> view: success_response
        view-->act: displayAllFacilityDetailsPage(success_response)
        else Not Valid
        ctrl --> view: error_response
        view-->act: getAddFacilityDetailPage(error_response)
        end


@enduml
