@startuml
title Update facility Detail
actor Admin as act
participant UpdateFacilityDetailPage as view
participant FacilityDetailController as ctrl
participant FacilityDetailModel as model

act -> view : openUpdateFacilityDetailPage()
view -> ctrl : getUpdateFacilityDetailPage(facility_details_id)
ctrl -> model : updateFacilityDetailPageGet(facility_details_id)
model --> ctrl : facility_detail_data
ctrl --> view : facility_detail_data
view --> act : displayUpdateFacilityDetailPage(facility_detail_data)

    act->view : inputUpdateFacilityDetailForm(facility_detail_data)
    view->ctrl : validateFacilityDetailData(facility_detail_data)
        alt Valid
        ctrl-->view:input_validated_response
        view->ctrl: updateFacilityDetail(facility_detail_data)
        ctrl->model: updateFacilityDetail(facility_detail_data)
        model --> ctrl: success_response
        ctrl --> view: success_response
        view-->act: displayAllFacilityDetailsPage(success_response)
        else Not Valid
        ctrl --> view: error_response
        view-->act: getUpdateFacilityDetailPage(error_response)
        end


@enduml
