@startuml
actor Admin as act
participant DeleteFacilityDetailConfirmationPage as view
participant FacilityDetailController as ctrl
participant FacilityDetailModel as model

act -> view : getDeleteFacilityDetailConfirmationPage()
act <-- view : displayDeleteFacilityDetailConfirmationPage()

    act->view : inputDeleteFacilityDetailConfirmationForm()
    alt Confirm
        view->ctrl: deleteFacilityDetail(id)
        ctrl->model: deleteFacilityDetail(id)
        model --> ctrl: success_response
        ctrl --> view: success_response
        view-->act: displayAllFacilityDetailsPage(success_response)
    else Back
        view-->act: displayAllFacilityDetailPage()
    end

@enduml
