@startuml
title View Boarding House Own by Owner
actor Owner as act
participant ViewAllBoardingsOwnerPage as view
participant BoardingsOwnerController as ctrl
participant BoardingsOwnerModel as model

act -> view: openAllBoardingsOwnerPage()
view -> ctrl: getAllBoardingsOwner()
ctrl -> model: getAllBoardinsgFromDB()
ctrl <-- model: all_boarding_houses_Owner
view <-- ctrl: all_boarding_houses_Owner
act <-- view: displayAllBoardingsOwnererPage(all_boarding_houses_Owner)

@enduml