@startuml
title View Boarding House Own by Manager
actor Manager as act
participant ViewAllBoardingsOwnPage as view
participant BoardingsOwnController as ctrl
participant BoardingsOwnModel as model

act -> view: openAllBoardingsOwnPage()
view -> ctrl: getAllBoardingsOwn()
ctrl -> model: getAllBoardinsgFromDB()
ctrl <-- model: all_boarding_houses_own
view <-- ctrl: all_boarding_houses_own
act <-- view: displayAllBoardingsOwnPage(all_boarding_houses_own)

@enduml