@startuml
actor Admin as act
participant ReapproveBoardingPage as view
participant BoardingController as ctrl
participant BoardingModel as model

act -> view : openReapproveBoardingPage()
view -> ctrl : getReapproveBoardingPage(boarding_id)
ctrl -> model : reapproveBoardingPageGet(boarding_id)
model --> ctrl : boarding_data
ctrl --> view : boarding_data
view --> act : displayReapproveBoardingPage(boarding_data)

    act->view : inputReapproveBoardingForm(boarding_data)
    view->ctrl : validateBoardingData(boarding_data)
        alt Valid
        ctrl-->view:input_validated_response
        view->ctrl: ReapproveBoarding(boarding_data)
        ctrl->model: ReapproveBoarding(boarding_data)
        model --> ctrl: success_response
        ctrl --> view: success_response
        view-->act: displayAllBoardingsOwnPage(success_response)
        else Not Valid
        ctrl --> view: error_response
        view-->act: getReapproveBoardingPage(error_response)
        end


@enduml
