@startuml
actor Owner as act
participant DisableBoardingConfirmationPage as view
participant BoardingController as ctrl
participant BoardingModel as model

act -> view : getDisableBoardingConfirmationPage()
act <-- view : displayDisableBoardingConfirmationPage()

    act->view : inputDisableBoardingConfirmationForm()
    view->ctrl: disableBoardingConfirmation(status:Disabled)
    ctrl->model: disableBoardingConfirmation(status:Disabled)
    model --> ctrl: success_response
    ctrl --> view: success_response
    view-->act: displayAllBoardingsOwnPage(success_response)

@enduml
