@startuml
title Request New Boarding House
actor Admin as act
participant AddBoardingPage as view
participant BoardingController as ctrl
participant BoardingModel as model

act -> view : getAddBoardingPage()
act <-- view : displayAddBoardingPage()

    act->view : inputAddBoardingForm()
    view->ctrl : validateBoardingData(boarding_data)
        alt Valid
        ctrl-->view:input_validated_response
        view->ctrl: addBoarding(boarding_data)
        ctrl->model: addBoarding(boarding_data)
        model --> ctrl: success_response
        ctrl --> view: success_response
        view-->act: displayAllBoardingPage(success_response)
        else Not Valid
        ctrl --> view: error_response
        view-->act: getAddBoardingPage(error_response)
        end


@enduml
