@startuml
title View tenant Detail
actor Manager as act
participant CurrentUserPage as view
participant TenantController as ctrl
participant UserModel as model

act -> view: openCurrentTenantPage()
view -> ctrl: getCurrentTenant()
ctrl -> model: getCurrentTenantFromDB()
ctrl <-- model: current_tenant
view <-- ctrl: current_tenant
act <-- view: displayCurrentUserPage(current_tenant)

@enduml