@startuml

|User|
start
    :View selected boarding house detail;

|System|
    :Show selected boarding house detail page;

|User|
    :Add this boarding house to wishlist;

|System|
    :Add boarding house to user wishlist;
    :Redirect user to selected boarding house detail page;
stop

@enduml