@startuml
title Boarding House (Manager)
|Manager|
    :See List Tenant Request;
    :Check Tenant Request;
    
    If (Manager Approve) then (Yes)
        :Manager Accept Tenant;

|Website|
        :Update Request Status;
        :Add Tenant To  List Of Tenant;
    else (No)
        :Manager Write Reason For Declined;
    Endif
    
|Manager|
    stop

@enduml
