@startuml
title Boarding House (Manager)
|Manager|
    :Select Boarding House;
    :Update Boarding House;
    :Manager Update Boarding House;
    :Submit;
        
|Website|
    :Update Boarding House To DB;
    stop
@enduml
