@startuml
title Boarding House (Admin)
|User|
start 
    :"Select Approve Boarding House";
|Website|
    : "Show Boarding House Details";
|User|
    :"Check Requested Boarding House Details";
    
    if (User Approve ?) is (Yes) then
|Website|
    : "Update Boarding House status to valid";
    : "Show Success Approving Boarding House Message";
    stop
else (No)
    : "User Write Reason For Declined";
|Website|
    : "Update Boarding House Declined_Reason";
    : "Show Success Declining Boarding House Message";
    stop
endif
@enduml