@startuml
title Boarding House (Admin)
partition User {
(*)  --> "See All Boarding Houses"
--> "Select Boarding House"
    If "User Input Choices" then
    --> [Approve New Boarding House] "Check Requested Boarding House Details"
     If "User Approve" then
        --> [Yes] "User Accept Boarding House"
        else
        --> [No] "User Write Reason For Declined"
        Endif
    else
    --> [Update Boarding House] "User Update Boarding House Details"
    --> "User Click Submit (Update)"
        
    else
    --> [Delete Boarding House] "Check Boarding House Deatils"
    --> "User Click Submit (Delete)"
    Endif
}

partition Website {
    "User Click Submit (Update)" --> If "Is Boarding House Details Valid ?" then
        --> [Valid] "System Update Selected Boarding House"
        --> "Show Success Update Boarding House Message"
        -->(*)
        else
        --> [Not Valid] "Show Failed Update Boarding House Message"
        --> (*)
    Endif
    

    "User Accept Boarding House" --> "Update Request Status"
    "User Write Reason For Declined" --> "Update Request Status"

    If "Is Status Approved ?" then
    --> [Yes] "Update Boarding House status to valid"
    --> "Show Success Approving Boarding House Message"
    -->(*)
    else
    --> [No] "Update Boarding House Declined_Reason" 
    --> "Show Success Declining Boarding House Message"
    --> (*)

    "User Click Submit (Delete)" --> "System Delete Selected Boarding House"
    --> "Show Success Deleting Boarding House Message"
    --> (*)
}
@enduml