@startuml
title Boarding House (Admin)
|User|
start 
    :"Select Delete Boarding House";
|Website|
    :"Show Boarding House Details";

|User|
    : "Check Boarding House Details";
    : "User Click Submit (Delete)";


|Website|
    : "System Delete Selected Boarding House";
    : "Show Success Deleting Boarding House Message";
    stop
@enduml