@startuml
title Boarding House (Admin)
partition User {
(*)  --> "User Click See All Boarding Houses"
}

partition Website {
"User Click See All Boarding Houses" --> "Show All Boarding Houses"
--> (*)
}
@enduml