@startuml
title Boarding House (Admin)

|User|
start
    : "Select Update Boarding House";

|Website|
    : "Show Boarding House Details";

|User|
    : "User Update Boarding House Details";
    : "User Click Submit (Update)";

|Website|
    if (Is Boarding House Details Valid ?) is (Valid) then
        : "System Update Selected Boarding House";
        : "Show Success Update Boarding House Message";
        stop
    else (Not Valid)
        : "Show Failed Update Boarding House Message";
        stop
@enduml