@startuml
title Boarding House (Admin)

(*)  --> "Click on View All Boarding House"
--> "Show All Boarding House"
-->"Show Choices"
If "User Input Choice" then
--> [Approve] "Show Requested Boarding House Detail"
--> "Show Approve Confirmation"
    If "User Click" then
    --> [Yes] "System Updates Selected Boarding House status to approved"
    --> "Show Success Approving Boarding House Message"
    --> "Show All Boarding House"
    else
    --> [No] "Show All Boarding House"
    Endif

else
--> [Delete] "Delete Boarding House Form"
--> "Show Delete Confirmation"
    If "User Click" then
    --> [Yes] "System Delete Selected Boarding House"
    --> "Show Success Delete Boarding House Message"
    --> "Show All Boarding House"
    else
    --> [No] "Show All Boarding House"
    Endif

else
--> [Update] "Show Update Form"
--> "User Update Boarding House Details"
--> "Show Update Confirmation"
    If "User Click" then
    --> [Yes] "Boarding House Validation"
        If "Is Valid ?" then
        --> [Valid] "System Update Selected Boarding House"
        --> "Show Success Update Boarding House Message"
        --> "Show All Boarding House"
        else
        --> [Not Valid] "Show Failed Update Boarding House Message"
        --> "Show Update Form"
        Endif
    else
    --> [No] "Show All Boarding House"
    Endif
Endif

-->(*)
@enduml
