@startuml
title Chat
|User|
start
    :See All Chat History;
    repeat
        :Click Specific Chat;
        :User Send New Message;
        backward :Press Back Button;
    repeat while (User Wants To See Other Chatting) is (Yes)
    
|Website|
    :Insert Message To DB;
stop
@enduml
