@startuml
title Chat
|User|
start
:Click on chat menu;
|System|
:return chat page;
|User|
:Click Specific Chat;
|System|
repeat :return chat with chat history;
|User|
:User Send New Message;
|System|
    :Insert Message To DB;
|User|
  backward :Click other chat;
if (User Wants To See Other Chat) then (Yes)
else (no)
   stop
endif
@enduml
