@startuml
|User|
start
    :See All Complain History;

    If (User Want To Complain) then (Create New Complain)
        :User Clicks Create New Complain;
        :User Input Complain Type and Description;

    else (View Current Complain)
        :User Click Specific Complain;
        :Click Specific Chat;
        :User Can See The Complain Status;
        
    endif
stop
@enduml
