@startuml
|Owner|
start
:Select Boarding House View All complain button;
|System|
:return all complain for that specific boarding house page;
|Owner|
:select specific complain;
|System|
:return complain detail page;
|Owner|
:Update Complain Status;
If (Complaint Has Been Resolved) then (Yes)
    :Mark As Resolved;
else (No)
    :Mark as On going;
endif
|System|
:Save to DB;
stop
@enduml