@startuml
title Edit Profile
|User|
start
    :Open Edit Profile Page;
|System|
    repeat :Show Edit Profile Page;

|User|
    :Update Profile;

|System|
    :Check Update Form Input;
    repeat while (Update Form Input is Acceptable) is (False)
        ->True;
        :Show Success Update Profile Message;
        :Update User Profile in Database;
stop
@enduml