@startuml
title Facilities Management View (Admin) 
|User|
start 
    :"User Click See All Facilities";


|Website|
    :"System Retrieves All Facilities Data";
    :"Show All Facilities";
stop

@enduml