@startuml
title Facility Update (Admin)
|User|
start 
    : "Select Update Facility";
|Website|
    :"Show Boarding House Details";
|User|  
    : "User Update Facility Details";
    : "User Click Submit (Update)";

|Website|
    if (Is Facility Details Valid ?) is (Valid) then
        : "System Update Selected Facility";
        : "Show Success Update Facility Message";
        stop
    else (Not Valid)
        : "Show Failed Update Facility Message";
        stop
    endif
@enduml