@startuml
title Facility Delete (Admin)
|User|
start 
    :"Select Delete Facility";
|Website|
    :"Show Facility Details";

|User|
    : "Check Facility Details";
    : "User Click Submit (Delete)";


|Website|
    : "System Delete Selected Facility";
    : "Show Success Deleting Facility Message";
    stop
@enduml