@startuml
title Facility Add (Admin)
|User|
start 
    : "Select Add Facility";
|Website|
    : "Show Add New Facility Form";
|User|
    : "User Add Facility Details";
    : "User Click Submit (Add)";

|Website|
    if (Is Facility Details Valid ?) is (Valid) then
        : "System Add Selected Facility";
        : "Show Success Add Facility Message";
        stop
        else (Not Valid)
        : "Show Failed Add Facility Message";
        stop
@enduml