@startuml

left to right direction
' top to bottom direction

title Facility Management (Admin)
@startuml
title Facility (Admin)
partition User {
(*)  --> "See All Facilities"
If "User Input Choices (Add New Facility)" then
--> [Click Add New] "Show Add New Facility Form"
--> "User Input New Facility Details"
--> "User Click Submit (Add New)"
else
--> [did not Click Add New] "Select Facility"
    If "User Input Choices" then
    --> [Update Facility] "User Update Facility Details"
    --> "User Click Submit (Update)"
        
    else
    --> [Delete Facility] "Check Facility Deatils"
    --> "User Click Submit (Delete)"
    Endif
}

partition Website {
    "User Click Submit (Add New)" --> If "Is Facility Details Valid ? (Add)" then
        --> [Valid] "System Add New Facility"
        --> "Show Success Add New Facility Message"
        -->(*)
        else
        --> [Not Valid] "Show Failed Add New Facility Message"
        --> (*)
    Endif

    "User Click Submit (Update)" --> If "Is Facility Details Valid ? (Update)" then
        --> [Valid] "System Update Selected Facility"
        --> "Show Success Update Facility Message"
        -->(*)
        else
        --> [Not Valid] "Show Failed Update Facility Message"
        --> (*)
    Endif


    "User Click Submit (Delete)" --> "System Delete Selected Facility"
    --> "Show Success Deleting Facility Message"
    --> (*)
}
@enduml
@enduml
