@startuml
title Facilities Management (Admin) View
partition User {
(*)  --> "User Click See All Facilities"
}

partition Website {
"User Click See All Facilities" --> "Show All Facilities"
--> (*)
}
@enduml