@startuml
|User|
start
    :Open Login Page;

|Website|
    :Show Login Page;

|User|
    :Insert Credentials;

|Website|
    :Check Credentials;

    if (Do Credentials Match the Database?) then (yes) 
            :Log user into the website;
            :Show Home Page;
            
    else (no) 
            :Show Login Page; 
    endif

stop
@enduml