@startuml

partition User {
    (*) --> "Open Login Page"
}

partition Website {
    "Open Login Page" --> "Show Login Page"    
}

partition User {
    "Show Login Page" --> "Insert Credentials"
}

partition Website {
    "Insert Credentials" --> "Check Credentials"
    
    "Check Credentials" --> if "Do Credentials Match the Database?" then 
    --> [true] "Log user into the website" 
    else 
    --> [false] "Show Login Page"
    
    "Log user into the website" --> "Show Home Page"
    
    "Show Home Page" --> (*)
}

@enduml