@startuml
|User|
start
    :Open Review Page;

|System|
    :Show Review Page;

|User|
    :Insert Review;
    :Give Rating;
    :Submit;

|System|
    :Insert To DB;
    :Show Home Page;

stop
@enduml