@startuml
title Make Complain
|Tenant|
start
:See All Complain History;

|System|
:Show all complain history;

|Tenant|
:Tenant Clicks Create New Complain;
|System|
:Show create new complain page;
|Tenant|
:Tenant Input Complain Type and Description;
|System|
if (Validate Input) then (Input valid)
    :Save to DB;
else (Input Invalid)
    :Show create new complain page with error;
endif

stop
@enduml
