@startuml

partition User {
    (*) --> "Open payment list page"
}

partition Website {
    "Open payment list page" --> "Show payment list page"
}

partition User {
   "Show payment list page" --> "Select one payment from the list"
}

partition Website {
   "Select one payment from the list" --> "Show payment details"
}

partition User {
  "Show payment details" --> "Select payment method"
  "Select payment method" --> ===GENERATE_PAYMENT_START===
}

partition Website {
    ===GENERATE_PAYMENT_START=== --> "Show user please wait page"
    --> ===GENERATE_PAYMENT_END===
    ===GENERATE_PAYMENT_START=== --> "hitting generate payment API"
}

partition Website {
    "hitting generate payment API" --> "receive payment details data"
    "receive payment details data" --> "generate payment details page"
    "generate payment details page" --> ===GENERATE_PAYMENT_END===
    ===GENERATE_PAYMENT_END=== --> "show payment details page"
    "show payment details page" --> ===ON_PAYMENT_START===
    ===ON_PAYMENT_START=== --> "show user please wait page"
    "show user please wait page" --> ===ON_PAYMENT_END===
    ===ON_PAYMENT_START=== --> "hit check payment API"
    "hit check payment API" --> if "payment success" then
    --> [true] "generate success payment page"
    --> ===ON_PAYMENT_END===
    else 
    --> [false] "generate failed payment page"
    --> ===ON_PAYMENT_END===
    endif
    --> "show success/failed payment page"
    --> (*)
}

partition User {
    ===ON_PAYMENT_START=== --> "do the payment"
    "do the payment" --> ===ON_PAYMENT_END===
}


@enduml