@startuml
title View All Payment (Owner)
|User|
start 
    :"Select Payment";

    : "Approve Payment Request";
    : "Check Payment Detail";
    If ("Owner Approve") is (No) then
        |User|
        : "Owner Input Reason for Declined";
        |Website|
        : "Update Payment Declined_Reason";
        : "Show Success Declining Payment Message";
        stop
    else (Yes)
        |Website|
        : "Update Payment Status to Approved";
        : "Show Success Approving Payment Message";
        stop
        endif

@enduml
