@startuml

partition User {
    (*) --> "Open Registration Page"
}

partition Website {
    "Open Registration Page" --> "Show Registration Page"
}

partition User {
    "Show Registration Page" --> "Insert Credentials"
}

partition Website {
    "Insert Credentials" --> "Check Form Input"
    "Check Form Input" --> if "Form Input is Acceptable" then 
    --> [true] "Soft Register Users"
    else
    --> [false] "Show Registration Page"

    "Soft Register Users" --> "Send Email Confirmation"
    "Send Email Confirmation" --> "Show Email Confirmation Page"
}

partition User {
    "Show Email Confirmation Page" --> "Confirm by Email"
}

partition Website {
    "Confirm by Email" --> "Hard Register User"
    "Hard Register User" --> "Show Login Page"
    "Show Login Page" --> (*)
}
@enduml