@startuml
|User|
start
    :Open Registration Page;

|Website|
    repeat :Show Registration Page;

|User|
    :Insert Credentials;

|Website|
    :Check Form Input;
    repeat while (Form Input is Acceptable?) is (no)
        ->yes;
    :Register Users to DB;
    :Show Login Page;
stop
@enduml