@startuml
title Boarding House (Manager)
|Owner|
start

    :Request Adding New Boarding House;
    :Insert Boarding House Detail;
    :Request Approval Boarding House;
|Admin|
    :Request Approval Boarding House;

    If (Request Approved) then (Yes)
        :Update Request Status;
    else (No)
        :Admin Write Reason For Declined;
    stop
    endif

|Website|
    :Add Boarding House To List Of Boarding House;
stop
@enduml
