@startuml
title Search Boarding House
|User|
    :Input location in search box;
    
|System|
    :receive user input;
    :query nearest boarding house from DB based on user input;
    if (Nearest Boarding House Found) then (Yes)
        :Show Search Result Page;
    else (No)
        :Show No Result Page;
    endif
    stop
@enduml