@startuml
title Boarding House
|Tenant|
    :Update Rating;
    :Update Review;
    :Click Save;
    
|System|
    :Validate Tenant input;
    If (is Tenant input valid?) then (Yes)
        :Save to database;
        :show Tenant boarding house page;
    else (No)
        :show Tenant Review page with error;
    endif
    stop
@enduml
