@startuml
title Boarding House
|User|
    :Update Rating;
    :Update Review;
    :Click Save;
    
|System|
    :Validate user input;
    If (is User input valid?) then (Yes)
        :Save to database;
        :show user boarding house page;
    else (No)
        :show user Review page with error;
    endif
    stop
@enduml
