@startuml
title View Review
|Tenant|
    :Select Boarding House Menu;
    
|System|
    :Show Boarding House Menu;

|Tenant|
    :Select Boarding House Review Menu;

|System|
    :Show review page;
    stop
@enduml
