@startuml
title View Complain
|Tenant|
start
:See All Complain History;

|System|
:Show all complain history;

|Tenant|
:Tenant Click Specific Complain;

|System|
:Show Tenant Specific complain detail;

|Tenant|
:Tenant Can See The Complain Status;

stop
@enduml
