@startuml

|User|
start
    :Checkout Boarding House Detail;

|Website|
    :Show Boarding House Detail page;

|User|
    :Add This Boarding House to Wishlist;

|Website|
    :Set Boarding House to User Wishlist;
    :Show Added to Wishlist Popup;
    repeat :Check Boarding House Capacity Periodically;
    repeat while (Boarding House has Empty Slot?) is (no)
        ->yes;
    :Log user into the website;
    :Show Home Page;
stop

@enduml