@startuml
title View All Transaction Types
|Admin|
start 
    :Admin Click See All Transaction Types;
|System|
    :System Retrieves All Transaction Types Data;
    :Show All Transaction Types Page;
    stop

@enduml