@startuml
actor Admin as act
participant ViewAllPaymentMethodsPage as view
participant PaymentMethodsController as ctrl
participant PaymentMethodsModel as model

act -> view: openAllPaymentMethodsPage()
view -> ctrl: getAllPaymentMethods()
ctrl -> model: getAllPaymentMethodsFromDB()
ctrl <-- model: all_payment_methods
view <-- ctrl: all_payment_methods
act <-- view: displayAllPaymentMethodsPage(all_payment_methods)

@enduml