@startuml
title Update Payment Method
actor Admin as act
participant UpdatePaymentMethodPage as view
participant PaymentMethodController as ctrl
participant PaymentMethodModel as model

act -> view : openUpdatePaymentMethodPage()
view -> ctrl : getUpdatePaymentMethodPage(payment_method_id)
ctrl -> model : updatePaymentMethodPageGet(payment_method_id)
model --> ctrl : payment_method_data
ctrl --> view : payment_method_data
view --> act : displayUpdatePaymentMethodPage(payment_method_data)

    act->view : inputUpdatePaymentMethodForm(payment_method_data)
    view->ctrl : validatePaymentMethodData(payment_method_data)
        alt Valid
        ctrl-->view:input_validated_response
        view->ctrl: updatePaymentMethod(payment_method_data)
        ctrl->model: updatePaymentMethod(payment_method_data)
        model --> ctrl: success_response
        ctrl --> view: success_response
        view-->act: displayAllPaymentMethodsPage(success_response)
        else Not Valid
        ctrl --> view: error_response
        view-->act: getUpdatePaymentMethodPage(error_response)
        end


@enduml
