@startuml
actor Admin as act
participant DeletePaymentMethodConfirmationPage as view
participant PaymentMethodController as ctrl
participant PaymentMethodModel as model

act -> view : getDeletePaymentMethodConfirmationPage()
act <-- view : displayDeletePaymentMethodConfirmationPage()

    act->view : inputDeletePaymentMethodConfirmationForm()
    alt Confirm
        view->ctrl: deletePaymentMethod(id)
        ctrl->model: deletePaymentMethod(id)
        model --> ctrl: success_response
        ctrl --> view: success_response
        view-->act: displayAllPaymentMethodsPage(success_response)
    else Back
        view-->act: displayAllPaymentMethodPage()
    end

@enduml
