@startuml
actor Admin as act
participant AddPaymentMethodPage as view
participant PaymentMethodController as ctrl
participant PaymentMethodModel as model

act -> view : getAddPaymentMethodPage()
act <-- view : displayAddPaymentMethodPage()

    act->view : inputAddPaymentMethodForm()
    view->ctrl : validatePaymentMethodData(payment_method_data)
        alt Valid
        ctrl-->view:input_validated_response
        view->ctrl: addPaymentMethod(payment_method_data)
        ctrl->model: addPaymentMethod(payment_method_data)
        model --> ctrl: success_response
        ctrl --> view: success_response
        view-->act: displayAllPaymentMethodsPage(success_response)
        else Not Valid
        ctrl --> view: error_response
        view-->act: getAddPaymentMethodPage(error_response)
        end


@enduml
