@startuml
actor Admin as act
participant ViewAllBoardingTypePage as view
participant BoardingTypeController as ctrl
participant BoardingTypeModel as model

act -> view: openAllBoardingTypePage()
view -> ctrl: getAllBoardingType()
ctrl -> model: getAllBoardingTypeFromDB()
ctrl <-- model: all_boarding_types
view <-- ctrl: all_boarding_types
act <-- view: displayAllBoardingTypePage(all_boarding_types)

@enduml