@startuml
actor Admin as act
participant UpdateBoardingTypePage as view
participant BoardingTypeController as ctrl
participant BoardingTypeModel as model

act -> view : openUpdateBoardingTypePage()
view -> ctrl : getUpdateBoardingTypePage(boarding_type_id)
ctrl -> model : updateBoardingTypePageGet(boarding_type_id)
model --> ctrl : Boarding_type_data
ctrl --> view : Boarding_type_data
view --> act : displayUpdateBoardingTypePage(boarding_type_data)

    act->view : inputUpdateBoardingTypeForm(boarding_type_data)
    view->ctrl : validateBoardingTypeData(boarding_type_data)
        alt Valid
        ctrl-->view:input_validated_response
        view->ctrl: updateBoardingType(boarding_type_data)
        ctrl->model: updateBoardingType(boarding_type_data)
        model --> ctrl: success_response
        ctrl --> view: success_response
        view-->act: displayAllBoardingTypesPage(success_response)
        else Not Valid
        ctrl --> view: error_response
        view-->act: getUpdateBoardingTypePage(error_response)
        end


@enduml
