@startuml
title Add Boarding Type 
actor Admin as act
participant AddBoardingTypePage as view
participant BoardingController as ctrl
participant BoardingModel as model

act -> view : getAddBoardingTypePage()
act <-- view : displayAddBoardingTypePage()

    act->view : inputAddBoardingTypeForm()
    view->ctrl : validateBoardingTypeData(boarding_type_data)
        alt Valid
        ctrl-->view:input_validated_response
        view->ctrl: addBoardingType(boarding_type_data)
        ctrl->model: addBoardingType(boarding_type_data)
        model --> ctrl: success_response
        ctrl --> view: success_response
        view-->act: displayAllBoardingTypePage(success_response)
        else Not Valid
        ctrl --> view: error_response
        view-->act: getAddBoardingTypePage(error_response)
        end


@enduml
