@startuml
actor Admin as act
participant DeleteBoardingTypeConfirmationPage as view
participant BoardingTypeController as ctrl
participant BoardingTypeModel as model

act -> view : getDeleteBoardingTypeConfirmationPage()
act <-- view : displayDeleteBoardingTypeConfirmationPage()

    act->view : inputDeleteBoardingTypeConfirmationForm()
    alt Confirm
        view->ctrl: deleteBoardingType(id)
        ctrl->model: deleteBoardingType(id)
        model --> ctrl: success_response
        ctrl --> view: success_response
        view-->act: displayAllBoardingTypePage(success_response)
    else Back
        view-->act: displayAllBoardingTypePage()
    end

@enduml
