@startuml
title Add Transaction Type
actor Admin as act
participant AddTransactionTypePage as view
participant TransactionTypeController as ctrl
participant TransactionTypeModel as model

act -> view : getAddTransactionTypePage()
act <-- view : displayAddTransactionTypePage()

    act->view : inputAddTransactionTypeForm()
    view->ctrl : validateTransactionTypeData(transaction_type_data)
        alt Valid
        ctrl-->view:input_validated_response
        view->ctrl: addTransactionType(transaction_type_data)
        ctrl->model: addTransactionType(transaction_type_data)
        model --> ctrl: success_response
        ctrl --> view: success_response
        view-->act: displayAllTransactionTypesPage(success_response)
        else Not Valid
        ctrl --> view: error_response
        view-->act: getAddTransactionTypePage(error_response)
        end


@enduml
