@startuml
actor Admin as act
participant ViewAllTransactionTypesPage as view
participant TransactionTypesController as ctrl
participant TransactionTypesModel as model

view -> ctrl: getAllTransactionTypes()
ctrl -> model: getAllTransactionTypesFromDB()
ctrl <-- model: all_transaction_types
view <-- ctrl: all_transaction_types
act <-- view: displayAllTransactionTypesPage(all_transaction_types)

@enduml