@startuml
actor Admin as act
participant UpdateTransactionTypePage as view
participant TransactionTypeController as ctrl
participant TransactionTypeModel as model

act -> view : openUpdateTransactionTypePage()
view -> ctrl : getUpdateTransactionTypePage(transaction_type_id)
ctrl -> model : updateTransactionTypePageGet(transaction_type_id)
model --> ctrl : transaction_type_data
ctrl --> view : transaction_type_data
view --> act : displayUpdateTransactionTypePage(transaction_type_data)

    act->view : inputUpdateTransactionTypeForm(transaction_type_data)
    view->ctrl : validateTransactionTypeData(transaction_type_data)
        alt Valid
        ctrl-->view:input_validated_response
        view->ctrl: updateTransactionType(transaction_type_data)
        ctrl->model: updateTransactionType(transaction_type_data)
        model --> ctrl: success_response
        ctrl --> view: success_response
        view-->act: displayAllTransactionTypesPage(success_response)
        else Not Valid
        ctrl --> view: error_response
        view-->act: getUpdateTransactionTypePage(error_response)
        end


@enduml
