@startuml
title Delete Transaction Type
actor Admin as act
participant DeleteTransactionTypeConfirmationPage as view
participant TransactionTypeController as ctrl
participant TransactionTypeModel as model

act -> view : getDeleteTransactionTypeConfirmationPage()
act <-- view : displayDeleteTransactionTypeConfirmationPage()

    act->view : inputDeleteTransactionTypeConfirmationForm()
    alt Confirm
        view->ctrl: deleteTransactionType(id)
        ctrl->model: deleteTransactionType(id)
        model --> ctrl: success_response
        ctrl --> view: success_response
        view-->act: displayAllTransactionTypePage(success_response)
    else Back
        view-->act: displayAllTransactionTypePage()
    end

@enduml
