@startuml
title Cancel Payment Invoice
|Owner & Manager|
start
:Select Boarding House for Detail;
|Website|
:Return Boarding House Detail;
|Owner & Manager|
:Select Cancel Payment;

|Website|
if(Cancellation is Possible) then (Possible)
    :Cancel Payment at DB;
    :Update view;
else (Not Possible)
    stop
endif
:Show response message;
stop
@enduml