@startuml
title Make Payment Invoice
|Owner & Manager|
start
:Select Boarding House Page;
|Website|
:Return Boarding House Page;
|Owner & Manager|
:Select Add Payment for Boarding House;
|Website|
:Show Add Payment Page;
|Owner & Manager|
repeat
:Insert Payment Info;
|Website|
repeat while (Verify Payment) is (Invalid)
        ->Valid;
    :Add Payment in DB;
:Return Boaridng House Page;
:Show Respone Message;
stop
@enduml