@startuml
title Make Down Payment Invoice
|Owner & Manager|
start
:Accept Tenant;
|Website|
:Return Add Down Payment Page;
|Owner & Manager|
repeat
:Insert Payment Info;
|Website|
repeat while (Verify Payment) is (Invalid)
        ->Valid;
    :Add Payment in DB;
:Return Tenant Boarding Page;
:Show Respone Message;
stop
@enduml